/*
TimeLogic API | A World Time API

TimeLogic API | A World Time API. World time, timezone, calendar, duration, and signed response operations.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package timelogicdirectapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the BulkError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkError{}

// BulkError Per-item error wrapper used inside bulk arrays returned by bulk-capable routes.
type BulkError struct {
	Error ApiError `json:"error"`
	RequestId string `json:"request_id"`
	// Intentionally omitted from public API error responses to avoid exposing request timing; use request_id for support correlation.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Item string `json:"item"`
}

type _BulkError BulkError

// NewBulkError instantiates a new BulkError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkError(error_ ApiError, requestId string, item string) *BulkError {
	this := BulkError{}
	this.Error = error_
	this.RequestId = requestId
	this.Item = item
	return &this
}

// NewBulkErrorWithDefaults instantiates a new BulkError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkErrorWithDefaults() *BulkError {
	this := BulkError{}
	return &this
}

// GetError returns the Error field value
func (o *BulkError) GetError() ApiError {
	if o == nil {
		var ret ApiError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *BulkError) GetErrorOk() (*ApiError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *BulkError) SetError(v ApiError) {
	o.Error = v
}

// GetRequestId returns the RequestId field value
func (o *BulkError) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *BulkError) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *BulkError) SetRequestId(v string) {
	o.RequestId = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *BulkError) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkError) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *BulkError) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *BulkError) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetItem returns the Item field value
func (o *BulkError) GetItem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *BulkError) GetItemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *BulkError) SetItem(v string) {
	o.Item = v
}

func (o BulkError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["request_id"] = o.RequestId
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	toSerialize["item"] = o.Item
	return toSerialize, nil
}

func (o *BulkError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"request_id",
		"item",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkError := _BulkError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkError)

	if err != nil {
		return err
	}

	*o = BulkError(varBulkError)

	return err
}

type NullableBulkError struct {
	value *BulkError
	isSet bool
}

func (v NullableBulkError) Get() *BulkError {
	return v.value
}

func (v *NullableBulkError) Set(val *BulkError) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkError) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkError(val *BulkError) *NullableBulkError {
	return &NullableBulkError{value: val, isSet: true}
}

func (v NullableBulkError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


