/*
TimeLogic API | A World Time API

TimeLogic API | A World Time API. World time, timezone, calendar, duration, and signed response operations.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package timelogicdirectapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// TimePayloadBulkItem - One bulk array item, either a successful time payload or a per-item bulk error.
type TimePayloadBulkItem struct {
	BulkError *BulkError
	TimePayload *TimePayload
}

// BulkErrorAsTimePayloadBulkItem is a convenience function that returns BulkError wrapped in TimePayloadBulkItem
func BulkErrorAsTimePayloadBulkItem(v *BulkError) TimePayloadBulkItem {
	return TimePayloadBulkItem{
		BulkError: v,
	}
}

// TimePayloadAsTimePayloadBulkItem is a convenience function that returns TimePayload wrapped in TimePayloadBulkItem
func TimePayloadAsTimePayloadBulkItem(v *TimePayload) TimePayloadBulkItem {
	return TimePayloadBulkItem{
		TimePayload: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TimePayloadBulkItem) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BulkError
	err = newStrictDecoder(data).Decode(&dst.BulkError)
	if err == nil {
		jsonBulkError, _ := json.Marshal(dst.BulkError)
		if string(jsonBulkError) == "{}" { // empty struct
			dst.BulkError = nil
		} else {
			if err = validator.Validate(dst.BulkError); err != nil {
				dst.BulkError = nil
			} else {
				match++
			}
		}
	} else {
		dst.BulkError = nil
	}

	// try to unmarshal data into TimePayload
	err = newStrictDecoder(data).Decode(&dst.TimePayload)
	if err == nil {
		jsonTimePayload, _ := json.Marshal(dst.TimePayload)
		if string(jsonTimePayload) == "{}" { // empty struct
			dst.TimePayload = nil
		} else {
			if err = validator.Validate(dst.TimePayload); err != nil {
				dst.TimePayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimePayload = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BulkError = nil
		dst.TimePayload = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TimePayloadBulkItem)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TimePayloadBulkItem)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TimePayloadBulkItem) MarshalJSON() ([]byte, error) {
	if src.BulkError != nil {
		return json.Marshal(&src.BulkError)
	}

	if src.TimePayload != nil {
		return json.Marshal(&src.TimePayload)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TimePayloadBulkItem) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BulkError != nil {
		return obj.BulkError
	}

	if obj.TimePayload != nil {
		return obj.TimePayload
	}

	// all schemas are nil
	return nil
}

type NullableTimePayloadBulkItem struct {
	value *TimePayloadBulkItem
	isSet bool
}

func (v NullableTimePayloadBulkItem) Get() *TimePayloadBulkItem {
	return v.value
}

func (v *NullableTimePayloadBulkItem) Set(val *TimePayloadBulkItem) {
	v.value = val
	v.isSet = true
}

func (v NullableTimePayloadBulkItem) IsSet() bool {
	return v.isSet
}

func (v *NullableTimePayloadBulkItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimePayloadBulkItem(val *TimePayloadBulkItem) *NullableTimePayloadBulkItem {
	return &NullableTimePayloadBulkItem{value: val, isSet: true}
}

func (v NullableTimePayloadBulkItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimePayloadBulkItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


