/*
TimeLogic API | A World Time API

TimeLogic API | A World Time API. World time, timezone, calendar, duration, and signed response operations.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package timelogicdirectapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiffEndpointRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiffEndpointRef{}

// DiffEndpointRef Resolved endpoint reference for diff calculations. This object intentionally includes only the resolved epoch-millisecond instant.
type DiffEndpointRef struct {
	UnixMs int64 `json:"unix_ms"`
}

type _DiffEndpointRef DiffEndpointRef

// NewDiffEndpointRef instantiates a new DiffEndpointRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiffEndpointRef(unixMs int64) *DiffEndpointRef {
	this := DiffEndpointRef{}
	this.UnixMs = unixMs
	return &this
}

// NewDiffEndpointRefWithDefaults instantiates a new DiffEndpointRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiffEndpointRefWithDefaults() *DiffEndpointRef {
	this := DiffEndpointRef{}
	return &this
}

// GetUnixMs returns the UnixMs field value
func (o *DiffEndpointRef) GetUnixMs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UnixMs
}

// GetUnixMsOk returns a tuple with the UnixMs field value
// and a boolean to check if the value has been set.
func (o *DiffEndpointRef) GetUnixMsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnixMs, true
}

// SetUnixMs sets field value
func (o *DiffEndpointRef) SetUnixMs(v int64) {
	o.UnixMs = v
}

func (o DiffEndpointRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiffEndpointRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unix_ms"] = o.UnixMs
	return toSerialize, nil
}

func (o *DiffEndpointRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unix_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiffEndpointRef := _DiffEndpointRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiffEndpointRef)

	if err != nil {
		return err
	}

	*o = DiffEndpointRef(varDiffEndpointRef)

	return err
}

type NullableDiffEndpointRef struct {
	value *DiffEndpointRef
	isSet bool
}

func (v NullableDiffEndpointRef) Get() *DiffEndpointRef {
	return v.value
}

func (v *NullableDiffEndpointRef) Set(val *DiffEndpointRef) {
	v.value = val
	v.isSet = true
}

func (v NullableDiffEndpointRef) IsSet() bool {
	return v.isSet
}

func (v *NullableDiffEndpointRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiffEndpointRef(val *DiffEndpointRef) *NullableDiffEndpointRef {
	return &NullableDiffEndpointRef{value: val, isSet: true}
}

func (v NullableDiffEndpointRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiffEndpointRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


