/*
TimeLogic API — Direct Customer Access

Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package timelogicdirectapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// GetCurrentTime200Response - struct for GetCurrentTime200Response
type GetCurrentTime200Response struct {
	TimePayload *TimePayload
	TimePayloadBulkResponse *TimePayloadBulkResponse
}

// TimePayloadAsGetCurrentTime200Response is a convenience function that returns TimePayload wrapped in GetCurrentTime200Response
func TimePayloadAsGetCurrentTime200Response(v *TimePayload) GetCurrentTime200Response {
	return GetCurrentTime200Response{
		TimePayload: v,
	}
}

// TimePayloadBulkResponseAsGetCurrentTime200Response is a convenience function that returns TimePayloadBulkResponse wrapped in GetCurrentTime200Response
func TimePayloadBulkResponseAsGetCurrentTime200Response(v *TimePayloadBulkResponse) GetCurrentTime200Response {
	return GetCurrentTime200Response{
		TimePayloadBulkResponse: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetCurrentTime200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TimePayload
	err = newStrictDecoder(data).Decode(&dst.TimePayload)
	if err == nil {
		jsonTimePayload, _ := json.Marshal(dst.TimePayload)
		if string(jsonTimePayload) == "{}" { // empty struct
			dst.TimePayload = nil
		} else {
			if err = validator.Validate(dst.TimePayload); err != nil {
				dst.TimePayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimePayload = nil
	}

	// try to unmarshal data into TimePayloadBulkResponse
	err = newStrictDecoder(data).Decode(&dst.TimePayloadBulkResponse)
	if err == nil {
		jsonTimePayloadBulkResponse, _ := json.Marshal(dst.TimePayloadBulkResponse)
		if string(jsonTimePayloadBulkResponse) == "{}" { // empty struct
			dst.TimePayloadBulkResponse = nil
		} else {
			if err = validator.Validate(dst.TimePayloadBulkResponse); err != nil {
				dst.TimePayloadBulkResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimePayloadBulkResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TimePayload = nil
		dst.TimePayloadBulkResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetCurrentTime200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetCurrentTime200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetCurrentTime200Response) MarshalJSON() ([]byte, error) {
	if src.TimePayload != nil {
		return json.Marshal(&src.TimePayload)
	}

	if src.TimePayloadBulkResponse != nil {
		return json.Marshal(&src.TimePayloadBulkResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetCurrentTime200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TimePayload != nil {
		return obj.TimePayload
	}

	if obj.TimePayloadBulkResponse != nil {
		return obj.TimePayloadBulkResponse
	}

	// all schemas are nil
	return nil
}

type NullableGetCurrentTime200Response struct {
	value *GetCurrentTime200Response
	isSet bool
}

func (v NullableGetCurrentTime200Response) Get() *GetCurrentTime200Response {
	return v.value
}

func (v *NullableGetCurrentTime200Response) Set(val *GetCurrentTime200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCurrentTime200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCurrentTime200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCurrentTime200Response(val *GetCurrentTime200Response) *NullableGetCurrentTime200Response {
	return &NullableGetCurrentTime200Response{value: val, isSet: true}
}

func (v NullableGetCurrentTime200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCurrentTime200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


