/*
TimeLogic API | A World Time API

TimeLogic API | A World Time API. World time, timezone, calendar, duration, and signed response operations.

API version: 1.0.0
*/

// Code generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git); DO NOT EDIT.

package timelogicapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CalendarResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarResponse{}

// CalendarResponse struct for CalendarResponse
type CalendarResponse struct {
	Unix int64 `json:"unix"`
	UnixMs int64 `json:"unix_ms"`
	Utc time.Time `json:"utc"`
	IsoLocal NullableString `json:"iso_local"`
	Rfc2822 string `json:"rfc2822"`
	Human string `json:"human"`
	DayNumber int32 `json:"day_number"`
	DayShort string `json:"day_short"`
	DayFull string `json:"day_full"`
	Timezone NullableString `json:"timezone"`
	Formatted *string `json:"formatted,omitempty"`
	Year int32 `json:"year"`
	Month int32 `json:"month"`
	MonthName string `json:"month_name"`
	Day int32 `json:"day"`
	WeekNumber *int32 `json:"week_number,omitempty"`
}

type _CalendarResponse CalendarResponse

// NewCalendarResponse instantiates a new CalendarResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarResponse(unix int64, unixMs int64, utc time.Time, isoLocal NullableString, rfc2822 string, human string, dayNumber int32, dayShort string, dayFull string, timezone NullableString, year int32, month int32, monthName string, day int32) *CalendarResponse {
	this := CalendarResponse{}
	this.Unix = unix
	this.UnixMs = unixMs
	this.Utc = utc
	this.IsoLocal = isoLocal
	this.Rfc2822 = rfc2822
	this.Human = human
	this.DayNumber = dayNumber
	this.DayShort = dayShort
	this.DayFull = dayFull
	this.Timezone = timezone
	this.Year = year
	this.Month = month
	this.MonthName = monthName
	this.Day = day
	return &this
}

// NewCalendarResponseWithDefaults instantiates a new CalendarResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarResponseWithDefaults() *CalendarResponse {
	this := CalendarResponse{}
	return &this
}

// GetUnix returns the Unix field value
func (o *CalendarResponse) GetUnix() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Unix
}

// GetUnixOk returns a tuple with the Unix field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetUnixOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unix, true
}

// SetUnix sets field value
func (o *CalendarResponse) SetUnix(v int64) {
	o.Unix = v
}

// GetUnixMs returns the UnixMs field value
func (o *CalendarResponse) GetUnixMs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UnixMs
}

// GetUnixMsOk returns a tuple with the UnixMs field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetUnixMsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnixMs, true
}

// SetUnixMs sets field value
func (o *CalendarResponse) SetUnixMs(v int64) {
	o.UnixMs = v
}

// GetUtc returns the Utc field value
func (o *CalendarResponse) GetUtc() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Utc
}

// GetUtcOk returns a tuple with the Utc field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetUtcOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Utc, true
}

// SetUtc sets field value
func (o *CalendarResponse) SetUtc(v time.Time) {
	o.Utc = v
}

// GetIsoLocal returns the IsoLocal field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CalendarResponse) GetIsoLocal() string {
	if o == nil || o.IsoLocal.Get() == nil {
		var ret string
		return ret
	}

	return *o.IsoLocal.Get()
}

// GetIsoLocalOk returns a tuple with the IsoLocal field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarResponse) GetIsoLocalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsoLocal.Get(), o.IsoLocal.IsSet()
}

// SetIsoLocal sets field value
func (o *CalendarResponse) SetIsoLocal(v string) {
	o.IsoLocal.Set(&v)
}

// GetRfc2822 returns the Rfc2822 field value
func (o *CalendarResponse) GetRfc2822() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rfc2822
}

// GetRfc2822Ok returns a tuple with the Rfc2822 field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetRfc2822Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rfc2822, true
}

// SetRfc2822 sets field value
func (o *CalendarResponse) SetRfc2822(v string) {
	o.Rfc2822 = v
}

// GetHuman returns the Human field value
func (o *CalendarResponse) GetHuman() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Human
}

// GetHumanOk returns a tuple with the Human field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetHumanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Human, true
}

// SetHuman sets field value
func (o *CalendarResponse) SetHuman(v string) {
	o.Human = v
}

// GetDayNumber returns the DayNumber field value
func (o *CalendarResponse) GetDayNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DayNumber
}

// GetDayNumberOk returns a tuple with the DayNumber field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetDayNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayNumber, true
}

// SetDayNumber sets field value
func (o *CalendarResponse) SetDayNumber(v int32) {
	o.DayNumber = v
}

// GetDayShort returns the DayShort field value
func (o *CalendarResponse) GetDayShort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DayShort
}

// GetDayShortOk returns a tuple with the DayShort field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetDayShortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayShort, true
}

// SetDayShort sets field value
func (o *CalendarResponse) SetDayShort(v string) {
	o.DayShort = v
}

// GetDayFull returns the DayFull field value
func (o *CalendarResponse) GetDayFull() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DayFull
}

// GetDayFullOk returns a tuple with the DayFull field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetDayFullOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayFull, true
}

// SetDayFull sets field value
func (o *CalendarResponse) SetDayFull(v string) {
	o.DayFull = v
}

// GetTimezone returns the Timezone field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CalendarResponse) GetTimezone() string {
	if o == nil || o.Timezone.Get() == nil {
		var ret string
		return ret
	}

	return *o.Timezone.Get()
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarResponse) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timezone.Get(), o.Timezone.IsSet()
}

// SetTimezone sets field value
func (o *CalendarResponse) SetTimezone(v string) {
	o.Timezone.Set(&v)
}

// GetFormatted returns the Formatted field value if set, zero value otherwise.
func (o *CalendarResponse) GetFormatted() string {
	if o == nil || IsNil(o.Formatted) {
		var ret string
		return ret
	}
	return *o.Formatted
}

// GetFormattedOk returns a tuple with the Formatted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetFormattedOk() (*string, bool) {
	if o == nil || IsNil(o.Formatted) {
		return nil, false
	}
	return o.Formatted, true
}

// HasFormatted returns a boolean if a field has been set.
func (o *CalendarResponse) HasFormatted() bool {
	if o != nil && !IsNil(o.Formatted) {
		return true
	}

	return false
}

// SetFormatted gets a reference to the given string and assigns it to the Formatted field.
func (o *CalendarResponse) SetFormatted(v string) {
	o.Formatted = &v
}

// GetYear returns the Year field value
func (o *CalendarResponse) GetYear() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Year
}

// GetYearOk returns a tuple with the Year field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetYearOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Year, true
}

// SetYear sets field value
func (o *CalendarResponse) SetYear(v int32) {
	o.Year = v
}

// GetMonth returns the Month field value
func (o *CalendarResponse) GetMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Month
}

// GetMonthOk returns a tuple with the Month field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Month, true
}

// SetMonth sets field value
func (o *CalendarResponse) SetMonth(v int32) {
	o.Month = v
}

// GetMonthName returns the MonthName field value
func (o *CalendarResponse) GetMonthName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MonthName
}

// GetMonthNameOk returns a tuple with the MonthName field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetMonthNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MonthName, true
}

// SetMonthName sets field value
func (o *CalendarResponse) SetMonthName(v string) {
	o.MonthName = v
}

// GetDay returns the Day field value
func (o *CalendarResponse) GetDay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetDayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *CalendarResponse) SetDay(v int32) {
	o.Day = v
}

// GetWeekNumber returns the WeekNumber field value if set, zero value otherwise.
func (o *CalendarResponse) GetWeekNumber() int32 {
	if o == nil || IsNil(o.WeekNumber) {
		var ret int32
		return ret
	}
	return *o.WeekNumber
}

// GetWeekNumberOk returns a tuple with the WeekNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarResponse) GetWeekNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.WeekNumber) {
		return nil, false
	}
	return o.WeekNumber, true
}

// HasWeekNumber returns a boolean if a field has been set.
func (o *CalendarResponse) HasWeekNumber() bool {
	if o != nil && !IsNil(o.WeekNumber) {
		return true
	}

	return false
}

// SetWeekNumber gets a reference to the given int32 and assigns it to the WeekNumber field.
func (o *CalendarResponse) SetWeekNumber(v int32) {
	o.WeekNumber = &v
}

func (o CalendarResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unix"] = o.Unix
	toSerialize["unix_ms"] = o.UnixMs
	toSerialize["utc"] = o.Utc
	toSerialize["iso_local"] = o.IsoLocal.Get()
	toSerialize["rfc2822"] = o.Rfc2822
	toSerialize["human"] = o.Human
	toSerialize["day_number"] = o.DayNumber
	toSerialize["day_short"] = o.DayShort
	toSerialize["day_full"] = o.DayFull
	toSerialize["timezone"] = o.Timezone.Get()
	if !IsNil(o.Formatted) {
		toSerialize["formatted"] = o.Formatted
	}
	toSerialize["year"] = o.Year
	toSerialize["month"] = o.Month
	toSerialize["month_name"] = o.MonthName
	toSerialize["day"] = o.Day
	if !IsNil(o.WeekNumber) {
		toSerialize["week_number"] = o.WeekNumber
	}
	return toSerialize, nil
}

func (o *CalendarResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unix",
		"unix_ms",
		"utc",
		"iso_local",
		"rfc2822",
		"human",
		"day_number",
		"day_short",
		"day_full",
		"timezone",
		"year",
		"month",
		"month_name",
		"day",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalendarResponse := _CalendarResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCalendarResponse)

	if err != nil {
		return err
	}

	*o = CalendarResponse(varCalendarResponse)

	return err
}

type NullableCalendarResponse struct {
	value *CalendarResponse
	isSet bool
}

func (v NullableCalendarResponse) Get() *CalendarResponse {
	return v.value
}

func (v *NullableCalendarResponse) Set(val *CalendarResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarResponse(val *CalendarResponse) *NullableCalendarResponse {
	return &NullableCalendarResponse{value: val, isSet: true}
}

func (v NullableCalendarResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


