/*
TimeLogic API | A World Time API

Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package timelogicdirectapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JwksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JwksResponse{}

// JwksResponse struct for JwksResponse
type JwksResponse struct {
	Keys []JwkKey `json:"keys"`
}

type _JwksResponse JwksResponse

// NewJwksResponse instantiates a new JwksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJwksResponse(keys []JwkKey) *JwksResponse {
	this := JwksResponse{}
	this.Keys = keys
	return &this
}

// NewJwksResponseWithDefaults instantiates a new JwksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJwksResponseWithDefaults() *JwksResponse {
	this := JwksResponse{}
	return &this
}

// GetKeys returns the Keys field value
func (o *JwksResponse) GetKeys() []JwkKey {
	if o == nil {
		var ret []JwkKey
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *JwksResponse) GetKeysOk() ([]JwkKey, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *JwksResponse) SetKeys(v []JwkKey) {
	o.Keys = v
}

func (o JwksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JwksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *JwksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJwksResponse := _JwksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJwksResponse)

	if err != nil {
		return err
	}

	*o = JwksResponse(varJwksResponse)

	return err
}

type NullableJwksResponse struct {
	value *JwksResponse
	isSet bool
}

func (v NullableJwksResponse) Get() *JwksResponse {
	return v.value
}

func (v *NullableJwksResponse) Set(val *JwksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJwksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJwksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJwksResponse(val *JwksResponse) *NullableJwksResponse {
	return &NullableJwksResponse{value: val, isSet: true}
}

func (v NullableJwksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJwksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


