/*
TimeLogic API — Direct Customer Access

Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package timelogicdirectapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TimePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimePayload{}

// TimePayload Canonical single-target time payload.
type TimePayload struct {
	Unix int64 `json:"unix"`
	UnixMs int64 `json:"unix_ms"`
	Utc time.Time `json:"utc"`
	IsoLocal NullableString `json:"iso_local"`
	Rfc2822 string `json:"rfc2822"`
	Human string `json:"human"`
	DayNumber int32 `json:"day_number"`
	DayShort string `json:"day_short"`
	DayFull string `json:"day_full"`
	Timezone NullableString `json:"timezone"`
	Formatted *string `json:"formatted,omitempty"`
}

type _TimePayload TimePayload

// NewTimePayload instantiates a new TimePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimePayload(unix int64, unixMs int64, utc time.Time, isoLocal NullableString, rfc2822 string, human string, dayNumber int32, dayShort string, dayFull string, timezone NullableString) *TimePayload {
	this := TimePayload{}
	this.Unix = unix
	this.UnixMs = unixMs
	this.Utc = utc
	this.IsoLocal = isoLocal
	this.Rfc2822 = rfc2822
	this.Human = human
	this.DayNumber = dayNumber
	this.DayShort = dayShort
	this.DayFull = dayFull
	this.Timezone = timezone
	return &this
}

// NewTimePayloadWithDefaults instantiates a new TimePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimePayloadWithDefaults() *TimePayload {
	this := TimePayload{}
	return &this
}

// GetUnix returns the Unix field value
func (o *TimePayload) GetUnix() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Unix
}

// GetUnixOk returns a tuple with the Unix field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetUnixOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unix, true
}

// SetUnix sets field value
func (o *TimePayload) SetUnix(v int64) {
	o.Unix = v
}

// GetUnixMs returns the UnixMs field value
func (o *TimePayload) GetUnixMs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UnixMs
}

// GetUnixMsOk returns a tuple with the UnixMs field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetUnixMsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnixMs, true
}

// SetUnixMs sets field value
func (o *TimePayload) SetUnixMs(v int64) {
	o.UnixMs = v
}

// GetUtc returns the Utc field value
func (o *TimePayload) GetUtc() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Utc
}

// GetUtcOk returns a tuple with the Utc field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetUtcOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Utc, true
}

// SetUtc sets field value
func (o *TimePayload) SetUtc(v time.Time) {
	o.Utc = v
}

// GetIsoLocal returns the IsoLocal field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TimePayload) GetIsoLocal() string {
	if o == nil || o.IsoLocal.Get() == nil {
		var ret string
		return ret
	}

	return *o.IsoLocal.Get()
}

// GetIsoLocalOk returns a tuple with the IsoLocal field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimePayload) GetIsoLocalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsoLocal.Get(), o.IsoLocal.IsSet()
}

// SetIsoLocal sets field value
func (o *TimePayload) SetIsoLocal(v string) {
	o.IsoLocal.Set(&v)
}

// GetRfc2822 returns the Rfc2822 field value
func (o *TimePayload) GetRfc2822() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rfc2822
}

// GetRfc2822Ok returns a tuple with the Rfc2822 field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetRfc2822Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rfc2822, true
}

// SetRfc2822 sets field value
func (o *TimePayload) SetRfc2822(v string) {
	o.Rfc2822 = v
}

// GetHuman returns the Human field value
func (o *TimePayload) GetHuman() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Human
}

// GetHumanOk returns a tuple with the Human field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetHumanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Human, true
}

// SetHuman sets field value
func (o *TimePayload) SetHuman(v string) {
	o.Human = v
}

// GetDayNumber returns the DayNumber field value
func (o *TimePayload) GetDayNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DayNumber
}

// GetDayNumberOk returns a tuple with the DayNumber field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetDayNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayNumber, true
}

// SetDayNumber sets field value
func (o *TimePayload) SetDayNumber(v int32) {
	o.DayNumber = v
}

// GetDayShort returns the DayShort field value
func (o *TimePayload) GetDayShort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DayShort
}

// GetDayShortOk returns a tuple with the DayShort field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetDayShortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayShort, true
}

// SetDayShort sets field value
func (o *TimePayload) SetDayShort(v string) {
	o.DayShort = v
}

// GetDayFull returns the DayFull field value
func (o *TimePayload) GetDayFull() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DayFull
}

// GetDayFullOk returns a tuple with the DayFull field value
// and a boolean to check if the value has been set.
func (o *TimePayload) GetDayFullOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayFull, true
}

// SetDayFull sets field value
func (o *TimePayload) SetDayFull(v string) {
	o.DayFull = v
}

// GetTimezone returns the Timezone field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TimePayload) GetTimezone() string {
	if o == nil || o.Timezone.Get() == nil {
		var ret string
		return ret
	}

	return *o.Timezone.Get()
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimePayload) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timezone.Get(), o.Timezone.IsSet()
}

// SetTimezone sets field value
func (o *TimePayload) SetTimezone(v string) {
	o.Timezone.Set(&v)
}

// GetFormatted returns the Formatted field value if set, zero value otherwise.
func (o *TimePayload) GetFormatted() string {
	if o == nil || IsNil(o.Formatted) {
		var ret string
		return ret
	}
	return *o.Formatted
}

// GetFormattedOk returns a tuple with the Formatted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimePayload) GetFormattedOk() (*string, bool) {
	if o == nil || IsNil(o.Formatted) {
		return nil, false
	}
	return o.Formatted, true
}

// HasFormatted returns a boolean if a field has been set.
func (o *TimePayload) HasFormatted() bool {
	if o != nil && !IsNil(o.Formatted) {
		return true
	}

	return false
}

// SetFormatted gets a reference to the given string and assigns it to the Formatted field.
func (o *TimePayload) SetFormatted(v string) {
	o.Formatted = &v
}

func (o TimePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unix"] = o.Unix
	toSerialize["unix_ms"] = o.UnixMs
	toSerialize["utc"] = o.Utc
	toSerialize["iso_local"] = o.IsoLocal.Get()
	toSerialize["rfc2822"] = o.Rfc2822
	toSerialize["human"] = o.Human
	toSerialize["day_number"] = o.DayNumber
	toSerialize["day_short"] = o.DayShort
	toSerialize["day_full"] = o.DayFull
	toSerialize["timezone"] = o.Timezone.Get()
	if !IsNil(o.Formatted) {
		toSerialize["formatted"] = o.Formatted
	}
	return toSerialize, nil
}

func (o *TimePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unix",
		"unix_ms",
		"utc",
		"iso_local",
		"rfc2822",
		"human",
		"day_number",
		"day_short",
		"day_full",
		"timezone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimePayload := _TimePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimePayload)

	if err != nil {
		return err
	}

	*o = TimePayload(varTimePayload)

	return err
}

type NullableTimePayload struct {
	value *TimePayload
	isSet bool
}

func (v NullableTimePayload) Get() *TimePayload {
	return v.value
}

func (v *NullableTimePayload) Set(val *TimePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableTimePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableTimePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimePayload(val *TimePayload) *NullableTimePayload {
	return &NullableTimePayload{value: val, isSet: true}
}

func (v NullableTimePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


