/*
TimeLogic API | A World Time API

TimeLogic API | A World Time API. World time, timezone, calendar, duration, and signed response operations.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package timelogicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiffResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiffResponse{}

// DiffResponse struct for DiffResponse
type DiffResponse struct {
	Seconds int32 `json:"seconds"`
	Minutes int32 `json:"minutes"`
	Hours int32 `json:"hours"`
	Days int32 `json:"days"`
	// `forward` means `to` is after `from`. `backward` means `to` is before `from`. `same` means both sides resolve to the same instant.
	Direction string `json:"direction"`
	Human string `json:"human"`
	Formatted *string `json:"formatted,omitempty"`
	BusinessDays *int32 `json:"business_days,omitempty"`
	From DiffEndpointRef `json:"from"`
	To DiffEndpointRef `json:"to"`
}

type _DiffResponse DiffResponse

// NewDiffResponse instantiates a new DiffResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiffResponse(seconds int32, minutes int32, hours int32, days int32, direction string, human string, from DiffEndpointRef, to DiffEndpointRef) *DiffResponse {
	this := DiffResponse{}
	this.Seconds = seconds
	this.Minutes = minutes
	this.Hours = hours
	this.Days = days
	this.Direction = direction
	this.Human = human
	this.From = from
	this.To = to
	return &this
}

// NewDiffResponseWithDefaults instantiates a new DiffResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiffResponseWithDefaults() *DiffResponse {
	this := DiffResponse{}
	return &this
}

// GetSeconds returns the Seconds field value
func (o *DiffResponse) GetSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seconds, true
}

// SetSeconds sets field value
func (o *DiffResponse) SetSeconds(v int32) {
	o.Seconds = v
}

// GetMinutes returns the Minutes field value
func (o *DiffResponse) GetMinutes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Minutes
}

// GetMinutesOk returns a tuple with the Minutes field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Minutes, true
}

// SetMinutes sets field value
func (o *DiffResponse) SetMinutes(v int32) {
	o.Minutes = v
}

// GetHours returns the Hours field value
func (o *DiffResponse) GetHours() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Hours
}

// GetHoursOk returns a tuple with the Hours field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetHoursOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hours, true
}

// SetHours sets field value
func (o *DiffResponse) SetHours(v int32) {
	o.Hours = v
}

// GetDays returns the Days field value
func (o *DiffResponse) GetDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Days
}

// GetDaysOk returns a tuple with the Days field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Days, true
}

// SetDays sets field value
func (o *DiffResponse) SetDays(v int32) {
	o.Days = v
}

// GetDirection returns the Direction field value
func (o *DiffResponse) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *DiffResponse) SetDirection(v string) {
	o.Direction = v
}

// GetHuman returns the Human field value
func (o *DiffResponse) GetHuman() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Human
}

// GetHumanOk returns a tuple with the Human field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetHumanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Human, true
}

// SetHuman sets field value
func (o *DiffResponse) SetHuman(v string) {
	o.Human = v
}

// GetFormatted returns the Formatted field value if set, zero value otherwise.
func (o *DiffResponse) GetFormatted() string {
	if o == nil || IsNil(o.Formatted) {
		var ret string
		return ret
	}
	return *o.Formatted
}

// GetFormattedOk returns a tuple with the Formatted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetFormattedOk() (*string, bool) {
	if o == nil || IsNil(o.Formatted) {
		return nil, false
	}
	return o.Formatted, true
}

// HasFormatted returns a boolean if a field has been set.
func (o *DiffResponse) HasFormatted() bool {
	if o != nil && !IsNil(o.Formatted) {
		return true
	}

	return false
}

// SetFormatted gets a reference to the given string and assigns it to the Formatted field.
func (o *DiffResponse) SetFormatted(v string) {
	o.Formatted = &v
}

// GetBusinessDays returns the BusinessDays field value if set, zero value otherwise.
func (o *DiffResponse) GetBusinessDays() int32 {
	if o == nil || IsNil(o.BusinessDays) {
		var ret int32
		return ret
	}
	return *o.BusinessDays
}

// GetBusinessDaysOk returns a tuple with the BusinessDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetBusinessDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.BusinessDays) {
		return nil, false
	}
	return o.BusinessDays, true
}

// HasBusinessDays returns a boolean if a field has been set.
func (o *DiffResponse) HasBusinessDays() bool {
	if o != nil && !IsNil(o.BusinessDays) {
		return true
	}

	return false
}

// SetBusinessDays gets a reference to the given int32 and assigns it to the BusinessDays field.
func (o *DiffResponse) SetBusinessDays(v int32) {
	o.BusinessDays = &v
}

// GetFrom returns the From field value
func (o *DiffResponse) GetFrom() DiffEndpointRef {
	if o == nil {
		var ret DiffEndpointRef
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetFromOk() (*DiffEndpointRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *DiffResponse) SetFrom(v DiffEndpointRef) {
	o.From = v
}

// GetTo returns the To field value
func (o *DiffResponse) GetTo() DiffEndpointRef {
	if o == nil {
		var ret DiffEndpointRef
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *DiffResponse) GetToOk() (*DiffEndpointRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *DiffResponse) SetTo(v DiffEndpointRef) {
	o.To = v
}

func (o DiffResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiffResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["seconds"] = o.Seconds
	toSerialize["minutes"] = o.Minutes
	toSerialize["hours"] = o.Hours
	toSerialize["days"] = o.Days
	toSerialize["direction"] = o.Direction
	toSerialize["human"] = o.Human
	if !IsNil(o.Formatted) {
		toSerialize["formatted"] = o.Formatted
	}
	if !IsNil(o.BusinessDays) {
		toSerialize["business_days"] = o.BusinessDays
	}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *DiffResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"seconds",
		"minutes",
		"hours",
		"days",
		"direction",
		"human",
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiffResponse := _DiffResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiffResponse)

	if err != nil {
		return err
	}

	*o = DiffResponse(varDiffResponse)

	return err
}

type NullableDiffResponse struct {
	value *DiffResponse
	isSet bool
}

func (v NullableDiffResponse) Get() *DiffResponse {
	return v.value
}

func (v *NullableDiffResponse) Set(val *DiffResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDiffResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDiffResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiffResponse(val *DiffResponse) *NullableDiffResponse {
	return &NullableDiffResponse{value: val, isSet: true}
}

func (v NullableDiffResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiffResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


