# coding: utf-8

"""
    TimeLogic API — Direct Customer Access

    Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from timelogic_direct_api.models.diff_response import DiffResponse

class TestDiffResponse(unittest.TestCase):
    """DiffResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiffResponse:
        """Test DiffResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiffResponse`
        """
        model = DiffResponse()
        if include_optional:
            return DiffResponse(
                seconds = 56,
                minutes = 56,
                hours = 56,
                days = 56,
                direction = 'forward',
                human = '',
                formatted = '',
                business_days = 56,
                var_from = timelogic_direct_api.models.diff_endpoint_ref.DiffEndpointRef(
                    unix_ms = 56, ),
                to = timelogic_direct_api.models.diff_endpoint_ref.DiffEndpointRef(
                    unix_ms = 56, )
            )
        else:
            return DiffResponse(
                seconds = 56,
                minutes = 56,
                hours = 56,
                days = 56,
                direction = 'forward',
                human = '',
                var_from = timelogic_direct_api.models.diff_endpoint_ref.DiffEndpointRef(
                    unix_ms = 56, ),
                to = timelogic_direct_api.models.diff_endpoint_ref.DiffEndpointRef(
                    unix_ms = 56, ),
        )
        """

    def testDiffResponse(self):
        """Test DiffResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
