/*
 * TimeLogic API | A World Time API
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.timelogic.direct.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.timelogic.direct.model.TimezoneMatch;
import com.timelogic.direct.model.TimezoneOffsetResponse;
import com.timelogic.direct.model.TimezoneResolvedResponse;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.timelogic.direct.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "1970-01-01T00:00:00Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class GetTimezone200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GetTimezone200Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetTimezone200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetTimezone200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<TimezoneResolvedResponse> adapterTimezoneResolvedResponse = gson.getDelegateAdapter(this, TypeToken.get(TimezoneResolvedResponse.class));
            final TypeAdapter<TimezoneOffsetResponse> adapterTimezoneOffsetResponse = gson.getDelegateAdapter(this, TypeToken.get(TimezoneOffsetResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<GetTimezone200Response>() {
                @Override
                public void write(JsonWriter out, GetTimezone200Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `TimezoneResolvedResponse`
                    if (value.getActualInstance() instanceof TimezoneResolvedResponse) {
                        JsonElement element = adapterTimezoneResolvedResponse.toJsonTree((TimezoneResolvedResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TimezoneOffsetResponse`
                    if (value.getActualInstance() instanceof TimezoneOffsetResponse) {
                        JsonElement element = adapterTimezoneOffsetResponse.toJsonTree((TimezoneOffsetResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: TimezoneOffsetResponse, TimezoneResolvedResponse");
                }

                @Override
                public GetTimezone200Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize TimezoneResolvedResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TimezoneResolvedResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterTimezoneResolvedResponse;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'TimezoneResolvedResponse'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TimezoneResolvedResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TimezoneResolvedResponse'", e);
                    }
                    // deserialize TimezoneOffsetResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TimezoneOffsetResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterTimezoneOffsetResponse;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'TimezoneOffsetResponse'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TimezoneOffsetResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TimezoneOffsetResponse'", e);
                    }

                    if (match == 1) {
                        GetTimezone200Response ret = new GetTimezone200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for GetTimezone200Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public GetTimezone200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public GetTimezone200Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TimezoneResolvedResponse", TimezoneResolvedResponse.class);
        schemas.put("TimezoneOffsetResponse", TimezoneOffsetResponse.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return GetTimezone200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * TimezoneOffsetResponse, TimezoneResolvedResponse
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof TimezoneResolvedResponse) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TimezoneOffsetResponse) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be TimezoneOffsetResponse, TimezoneResolvedResponse");
    }

    /**
     * Get the actual instance, which can be the following:
     * TimezoneOffsetResponse, TimezoneResolvedResponse
     *
     * @return The actual instance (TimezoneOffsetResponse, TimezoneResolvedResponse)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TimezoneResolvedResponse`. If the actual instance is not `TimezoneResolvedResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TimezoneResolvedResponse`
     * @throws ClassCastException if the instance is not `TimezoneResolvedResponse`
     */
    public TimezoneResolvedResponse getTimezoneResolvedResponse() throws ClassCastException {
        return (TimezoneResolvedResponse)super.getActualInstance();
    }

    /**
     * Get the actual instance of `TimezoneOffsetResponse`. If the actual instance is not `TimezoneOffsetResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TimezoneOffsetResponse`
     * @throws ClassCastException if the instance is not `TimezoneOffsetResponse`
     */
    public TimezoneOffsetResponse getTimezoneOffsetResponse() throws ClassCastException {
        return (TimezoneOffsetResponse)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetTimezone200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with TimezoneResolvedResponse
        try {
            TimezoneResolvedResponse.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TimezoneResolvedResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TimezoneOffsetResponse
        try {
            TimezoneOffsetResponse.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TimezoneOffsetResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for GetTimezone200Response with oneOf schemas: TimezoneOffsetResponse, TimezoneResolvedResponse. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of GetTimezone200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetTimezone200Response
     * @throws IOException if the JSON string is invalid with respect to GetTimezone200Response
     */
    public static GetTimezone200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetTimezone200Response.class);
    }

    /**
     * Convert an instance of GetTimezone200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

