/**
 *
 * Please note:
 * This class is auto generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.timelogic.direct.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param code
 * @param message
 * @param details Optional implementation-specific detail payload.
 */


data class ApiError (

    @Json(name = "code")
    val code: ApiError.Code,

    @Json(name = "message")
    val message: kotlin.String,

    /* Optional implementation-specific detail payload. */
    @Json(name = "details")
    val details: kotlin.Any? = null

) {

    /**
     *
     *
     * Values: AMBIGUOUS_TARGET,MISSING_TARGET,INVALID_PARAMETER,INVALID_TIMESTAMP,DEPENDENCY_NOT_READY,SIGNING_NOT_READY,UNAUTHORIZED,INVALID_AUTH,METHOD_NOT_ALLOWED,NOT_FOUND,INTERNAL_ERROR,SUBSCRIPTION_INACTIVE,QUOTA_EXCEEDED
     */
    @JsonClass(generateAdapter = false)
    enum class Code(val value: kotlin.String) {
        @Json(name = "AMBIGUOUS_TARGET") AMBIGUOUS_TARGET("AMBIGUOUS_TARGET"),
        @Json(name = "MISSING_TARGET") MISSING_TARGET("MISSING_TARGET"),
        @Json(name = "INVALID_PARAMETER") INVALID_PARAMETER("INVALID_PARAMETER"),
        @Json(name = "INVALID_TIMESTAMP") INVALID_TIMESTAMP("INVALID_TIMESTAMP"),
        @Json(name = "DEPENDENCY_NOT_READY") DEPENDENCY_NOT_READY("DEPENDENCY_NOT_READY"),
        @Json(name = "SIGNING_NOT_READY") SIGNING_NOT_READY("SIGNING_NOT_READY"),
        @Json(name = "UNAUTHORIZED") UNAUTHORIZED("UNAUTHORIZED"),
        @Json(name = "INVALID_AUTH") INVALID_AUTH("INVALID_AUTH"),
        @Json(name = "METHOD_NOT_ALLOWED") METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
        @Json(name = "NOT_FOUND") NOT_FOUND("NOT_FOUND"),
        @Json(name = "INTERNAL_ERROR") INTERNAL_ERROR("INTERNAL_ERROR"),
        @Json(name = "SUBSCRIPTION_INACTIVE") SUBSCRIPTION_INACTIVE("SUBSCRIPTION_INACTIVE"),
        @Json(name = "QUOTA_EXCEEDED") QUOTA_EXCEEDED("QUOTA_EXCEEDED");
    }

}

