/**
 *
 * Please note:
 * This class is auto generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.timelogic.direct.api.models

import com.timelogic.direct.api.models.TimezoneMatch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Offset-based timezone lookup result with `matching_zones` for the current request-time offset match.
 *
 * @param unix
 * @param unixMs
 * @param utc
 * @param isoLocal
 * @param rfc2822
 * @param human
 * @param dayNumber
 * @param dayShort
 * @param dayFull
 * @param timezone
 * @param offset
 * @param dst
 * @param matchingZones
 * @param formatted
 */


data class TimezoneOffsetResponse (

    @Json(name = "unix")
    val unix: kotlin.Long,

    @Json(name = "unix_ms")
    val unixMs: kotlin.Long,

    @Json(name = "utc")
    val utc: java.time.OffsetDateTime,

    @Json(name = "iso_local")
    val isoLocal: kotlin.String?,

    @Json(name = "rfc2822")
    val rfc2822: kotlin.String,

    @Json(name = "human")
    val human: kotlin.String,

    @Json(name = "day_number")
    val dayNumber: kotlin.Int,

    @Json(name = "day_short")
    val dayShort: kotlin.String,

    @Json(name = "day_full")
    val dayFull: kotlin.String,

    @Json(name = "timezone")
    val timezone: kotlin.String?,

    @Json(name = "offset")
    val offset: kotlin.Int,

    @Json(name = "dst")
    val dst: kotlin.Boolean,

    @Json(name = "matching_zones")
    val matchingZones: kotlin.collections.List<TimezoneMatch>,

    @Json(name = "formatted")
    val formatted: kotlin.String? = null

) {


}

