//
// GetCurrentTime200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetCurrentTime200Response: Codable, JSONEncodable, Hashable {
    case typeTimePayload(TimePayload)
    case typeTimePayloadBulkResponse(TimePayloadBulkResponse)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTimePayload(let value):
            try container.encode(value)
        case .typeTimePayloadBulkResponse(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TimePayload.self) {
            self = .typeTimePayload(value)
        } else if let value = try? container.decode(TimePayloadBulkResponse.self) {
            self = .typeTimePayloadBulkResponse(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetCurrentTime200Response"))
        }
    }
}

