//
// GetTimezone200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetTimezone200Response: Codable, JSONEncodable, Hashable {
    case typeTimezoneOffsetResponse(TimezoneOffsetResponse)
    case typeTimezoneResolvedResponse(TimezoneResolvedResponse)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTimezoneOffsetResponse(let value):
            try container.encode(value)
        case .typeTimezoneResolvedResponse(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TimezoneOffsetResponse.self) {
            self = .typeTimezoneOffsetResponse(value)
        } else if let value = try? container.decode(TimezoneResolvedResponse.self) {
            self = .typeTimezoneResolvedResponse(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetTimezone200Response"))
        }
    }
}

