//
// JwkKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JwkKey: Codable, JSONEncodable, Hashable {

    public enum Kty: String, Codable, CaseIterable {
        case okp = "OKP"
    }
    public enum Crv: String, Codable, CaseIterable {
        case ed25519 = "Ed25519"
    }
    public enum Alg: String, Codable, CaseIterable {
        case edDSA = "EdDSA"
    }
    public enum Use: String, Codable, CaseIterable {
        case sig = "sig"
    }
    public var kty: Kty
    public var crv: Crv
    public var alg: Alg
    public var use: Use
    public var kid: String
    public var x: String

    public init(kty: Kty, crv: Crv, alg: Alg, use: Use, kid: String, x: String) {
        self.kty = kty
        self.crv = crv
        self.alg = alg
        self.use = use
        self.kid = kid
        self.x = x
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kty
        case crv
        case alg
        case use
        case kid
        case x
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kty, forKey: .kty)
        try container.encode(crv, forKey: .crv)
        try container.encode(alg, forKey: .alg)
        try container.encode(use, forKey: .use)
        try container.encode(kid, forKey: .kid)
        try container.encode(x, forKey: .x)
    }
}

