//
// JwksResponse.swift
//
// Generated by the TimeLogic API SDK generator
// https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JwksResponse: Codable, JSONEncodable, Hashable {

    public var keys: [JwkKey]

    public init(keys: [JwkKey]) {
        self.keys = keys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keys
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keys, forKey: .keys)
    }
}

