/*
 * TimeLogic API — Direct Customer Access
 *
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TimeLogic.DirectApi.Model;
using TimeLogic.DirectApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TimeLogic.DirectApi.Test.Model
{
    /// <summary>
    ///  Class for testing JwkKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JwkKeyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JwkKey
        //private JwkKey instance;

        public JwkKeyTests()
        {
            // TODO uncomment below to create an instance of JwkKey
            //instance = new JwkKey();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JwkKey
        /// </summary>
        [Fact]
        public void JwkKeyInstanceTest()
        {
            // TODO uncomment below to test "IsType" JwkKey
            //Assert.IsType<JwkKey>(instance);
        }

        /// <summary>
        /// Test the property 'Kty'
        /// </summary>
        [Fact]
        public void KtyTest()
        {
            // TODO unit test for the property 'Kty'
        }

        /// <summary>
        /// Test the property 'Crv'
        /// </summary>
        [Fact]
        public void CrvTest()
        {
            // TODO unit test for the property 'Crv'
        }

        /// <summary>
        /// Test the property 'Alg'
        /// </summary>
        [Fact]
        public void AlgTest()
        {
            // TODO unit test for the property 'Alg'
        }

        /// <summary>
        /// Test the property 'Use'
        /// </summary>
        [Fact]
        public void UseTest()
        {
            // TODO unit test for the property 'Use'
        }

        /// <summary>
        /// Test the property 'Kid'
        /// </summary>
        [Fact]
        public void KidTest()
        {
            // TODO unit test for the property 'Kid'
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
    }
}
