/*
 * TimeLogic API — Direct Customer Access
 *
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TimeLogic.DirectApi.Model;
using TimeLogic.DirectApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TimeLogic.DirectApi.Test.Model
{
    /// <summary>
    ///  Class for testing TimePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimePayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimePayload
        //private TimePayload instance;

        public TimePayloadTests()
        {
            // TODO uncomment below to create an instance of TimePayload
            //instance = new TimePayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimePayload
        /// </summary>
        [Fact]
        public void TimePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimePayload
            //Assert.IsType<TimePayload>(instance);
        }

        /// <summary>
        /// Test the property 'Unix'
        /// </summary>
        [Fact]
        public void UnixTest()
        {
            // TODO unit test for the property 'Unix'
        }

        /// <summary>
        /// Test the property 'UnixMs'
        /// </summary>
        [Fact]
        public void UnixMsTest()
        {
            // TODO unit test for the property 'UnixMs'
        }

        /// <summary>
        /// Test the property 'Utc'
        /// </summary>
        [Fact]
        public void UtcTest()
        {
            // TODO unit test for the property 'Utc'
        }

        /// <summary>
        /// Test the property 'IsoLocal'
        /// </summary>
        [Fact]
        public void IsoLocalTest()
        {
            // TODO unit test for the property 'IsoLocal'
        }

        /// <summary>
        /// Test the property 'Rfc2822'
        /// </summary>
        [Fact]
        public void Rfc2822Test()
        {
            // TODO unit test for the property 'Rfc2822'
        }

        /// <summary>
        /// Test the property 'Human'
        /// </summary>
        [Fact]
        public void HumanTest()
        {
            // TODO unit test for the property 'Human'
        }

        /// <summary>
        /// Test the property 'DayNumber'
        /// </summary>
        [Fact]
        public void DayNumberTest()
        {
            // TODO unit test for the property 'DayNumber'
        }

        /// <summary>
        /// Test the property 'DayShort'
        /// </summary>
        [Fact]
        public void DayShortTest()
        {
            // TODO unit test for the property 'DayShort'
        }

        /// <summary>
        /// Test the property 'DayFull'
        /// </summary>
        [Fact]
        public void DayFullTest()
        {
            // TODO unit test for the property 'DayFull'
        }

        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

        /// <summary>
        /// Test the property 'Formatted'
        /// </summary>
        [Fact]
        public void FormattedTest()
        {
            // TODO unit test for the property 'Formatted'
        }
    }
}
