=begin
#TimeLogic API | A World Time API

# Official public API contract for TimeLogic API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TimeLogic::Api::ApiError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TimeLogic::Api::ApiError do
  let(:instance) { TimeLogic::Api::ApiError.new }

  describe 'test an instance of ApiError' do
    it 'should create an instance of ApiError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TimeLogic::Api::ApiError)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AMBIGUOUS_TARGET", "MISSING_TARGET", "INVALID_PARAMETER", "INVALID_TIMESTAMP", "DEPENDENCY_NOT_READY", "SIGNING_NOT_READY", "UNAUTHORIZED", "INVALID_AUTH", "METHOD_NOT_ALLOWED", "NOT_FOUND", "INTERNAL_ERROR", "SUBSCRIPTION_INACTIVE", "QUOTA_EXCEEDED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
