=begin
#TimeLogic API | A World Time API

#Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TimeLogic::DirectApi::ApiError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TimeLogic::DirectApi::ApiError do
  let(:instance) { TimeLogic::DirectApi::ApiError.new }

  describe 'test an instance of ApiError' do
    it 'should create an instance of ApiError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TimeLogic::DirectApi::ApiError)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AMBIGUOUS_TARGET", "MISSING_TARGET", "INVALID_PARAMETER", "INVALID_TIMESTAMP", "DEPENDENCY_NOT_READY", "SIGNING_NOT_READY", "UNAUTHORIZED", "INVALID_AUTH", "METHOD_NOT_ALLOWED", "NOT_FOUND", "INTERNAL_ERROR", "SUBSCRIPTION_INACTIVE", "QUOTA_EXCEEDED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
