=begin
#TimeLogic API | A World Time API

# Official public API contract for TimeLogic API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TimeLogic::Api::BulkError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TimeLogic::Api::BulkError do
  let(:instance) { TimeLogic::Api::BulkError.new }

  describe 'test an instance of BulkError' do
    it 'should create an instance of BulkError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TimeLogic::Api::BulkError)
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "request_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "timestamp"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "item"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
