=begin
#TimeLogic API | A World Time API

# Official public API contract for TimeLogic API.

The version of the OpenAPI document: 1.0.0

Generated by: https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TimeLogic::Api::DiffEndpointRef
# Automatically generated by the TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git)
# Please update as you see appropriate
describe TimeLogic::Api::DiffEndpointRef do
  let(:instance) { TimeLogic::Api::DiffEndpointRef.new }

  describe 'test an instance of DiffEndpointRef' do
    it 'should create an instance of DiffEndpointRef' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TimeLogic::Api::DiffEndpointRef)
    end
  end

  describe 'test attribute "unix_ms"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
