=begin
#TimeLogic API | A World Time API

# Official public API contract for TimeLogic API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TimeLogic::Api::TimePayloadBulkResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TimeLogic::Api::TimePayloadBulkResponse do
  let(:instance) { TimeLogic::Api::TimePayloadBulkResponse.new }

  describe 'test an instance of TimePayloadBulkResponse' do
    it 'should create an instance of TimePayloadBulkResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TimeLogic::Api::TimePayloadBulkResponse)
    end
  end

end
