/*
 * TimeLogic API | A World Time API
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.timelogic.direct.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CalendarResponse
 */
public class CalendarResponseTest {
    private final CalendarResponse model = new CalendarResponse();

    /**
     * Model tests for CalendarResponse
     */
    @Test
    public void testCalendarResponse() {
        // TODO: test CalendarResponse
    }

    /**
     * Test the property 'unix'
     */
    @Test
    public void unixTest() {
        // TODO: test unix
    }

    /**
     * Test the property 'unixMs'
     */
    @Test
    public void unixMsTest() {
        // TODO: test unixMs
    }

    /**
     * Test the property 'utc'
     */
    @Test
    public void utcTest() {
        // TODO: test utc
    }

    /**
     * Test the property 'isoLocal'
     */
    @Test
    public void isoLocalTest() {
        // TODO: test isoLocal
    }

    /**
     * Test the property 'rfc2822'
     */
    @Test
    public void rfc2822Test() {
        // TODO: test rfc2822
    }

    /**
     * Test the property 'human'
     */
    @Test
    public void humanTest() {
        // TODO: test human
    }

    /**
     * Test the property 'dayNumber'
     */
    @Test
    public void dayNumberTest() {
        // TODO: test dayNumber
    }

    /**
     * Test the property 'dayShort'
     */
    @Test
    public void dayShortTest() {
        // TODO: test dayShort
    }

    /**
     * Test the property 'dayFull'
     */
    @Test
    public void dayFullTest() {
        // TODO: test dayFull
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'formatted'
     */
    @Test
    public void formattedTest() {
        // TODO: test formatted
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'monthName'
     */
    @Test
    public void monthNameTest() {
        // TODO: test monthName
    }

    /**
     * Test the property 'day'
     */
    @Test
    public void dayTest() {
        // TODO: test day
    }

    /**
     * Test the property 'weekNumber'
     */
    @Test
    public void weekNumberTest() {
        // TODO: test weekNumber
    }

}
