=begin
#TimeLogic API | A World Time API

#Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module TimeLogic::DirectApi
  # Standard single-target timezone resolution payload.
  class TimezoneResolvedResponse
    attr_accessor :unix

    attr_accessor :unix_ms

    attr_accessor :utc

    attr_accessor :iso_local

    attr_accessor :rfc2822

    attr_accessor :human

    attr_accessor :day_number

    attr_accessor :day_short

    attr_accessor :day_full

    attr_accessor :timezone

    attr_accessor :formatted

    attr_accessor :offset

    attr_accessor :dst

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'unix' => :'unix',
        :'unix_ms' => :'unix_ms',
        :'utc' => :'utc',
        :'iso_local' => :'iso_local',
        :'rfc2822' => :'rfc2822',
        :'human' => :'human',
        :'day_number' => :'day_number',
        :'day_short' => :'day_short',
        :'day_full' => :'day_full',
        :'timezone' => :'timezone',
        :'formatted' => :'formatted',
        :'offset' => :'offset',
        :'dst' => :'dst'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'unix' => :'Integer',
        :'unix_ms' => :'Integer',
        :'utc' => :'Time',
        :'iso_local' => :'String',
        :'rfc2822' => :'String',
        :'human' => :'String',
        :'day_number' => :'Integer',
        :'day_short' => :'String',
        :'day_full' => :'String',
        :'timezone' => :'String',
        :'formatted' => :'String',
        :'offset' => :'Integer',
        :'dst' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'iso_local',
        :'timezone',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'TimePayload'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TimeLogic::DirectApi::TimezoneResolvedResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TimeLogic::DirectApi::TimezoneResolvedResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'unix')
        self.unix = attributes[:'unix']
      else
        self.unix = nil
      end

      if attributes.key?(:'unix_ms')
        self.unix_ms = attributes[:'unix_ms']
      else
        self.unix_ms = nil
      end

      if attributes.key?(:'utc')
        self.utc = attributes[:'utc']
      else
        self.utc = nil
      end

      if attributes.key?(:'iso_local')
        self.iso_local = attributes[:'iso_local']
      else
        self.iso_local = nil
      end

      if attributes.key?(:'rfc2822')
        self.rfc2822 = attributes[:'rfc2822']
      else
        self.rfc2822 = nil
      end

      if attributes.key?(:'human')
        self.human = attributes[:'human']
      else
        self.human = nil
      end

      if attributes.key?(:'day_number')
        self.day_number = attributes[:'day_number']
      else
        self.day_number = nil
      end

      if attributes.key?(:'day_short')
        self.day_short = attributes[:'day_short']
      else
        self.day_short = nil
      end

      if attributes.key?(:'day_full')
        self.day_full = attributes[:'day_full']
      else
        self.day_full = nil
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      else
        self.timezone = nil
      end

      if attributes.key?(:'formatted')
        self.formatted = attributes[:'formatted']
      end

      if attributes.key?(:'offset')
        self.offset = attributes[:'offset']
      else
        self.offset = nil
      end

      if attributes.key?(:'dst')
        self.dst = attributes[:'dst']
      else
        self.dst = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @unix.nil?
        invalid_properties.push('invalid value for "unix", unix cannot be nil.')
      end

      if @unix_ms.nil?
        invalid_properties.push('invalid value for "unix_ms", unix_ms cannot be nil.')
      end

      if @utc.nil?
        invalid_properties.push('invalid value for "utc", utc cannot be nil.')
      end

      if @rfc2822.nil?
        invalid_properties.push('invalid value for "rfc2822", rfc2822 cannot be nil.')
      end

      if @human.nil?
        invalid_properties.push('invalid value for "human", human cannot be nil.')
      end

      if @day_number.nil?
        invalid_properties.push('invalid value for "day_number", day_number cannot be nil.')
      end

      if @day_number > 7
        invalid_properties.push('invalid value for "day_number", must be smaller than or equal to 7.')
      end

      if @day_number < 1
        invalid_properties.push('invalid value for "day_number", must be greater than or equal to 1.')
      end

      if @day_short.nil?
        invalid_properties.push('invalid value for "day_short", day_short cannot be nil.')
      end

      if @day_full.nil?
        invalid_properties.push('invalid value for "day_full", day_full cannot be nil.')
      end

      if @offset.nil?
        invalid_properties.push('invalid value for "offset", offset cannot be nil.')
      end

      if @dst.nil?
        invalid_properties.push('invalid value for "dst", dst cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @unix.nil?
      return false if @unix_ms.nil?
      return false if @utc.nil?
      return false if @rfc2822.nil?
      return false if @human.nil?
      return false if @day_number.nil?
      return false if @day_number > 7
      return false if @day_number < 1
      return false if @day_short.nil?
      return false if @day_full.nil?
      return false if @offset.nil?
      return false if @dst.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] day_number Value to be assigned
    def day_number=(day_number)
      if day_number.nil?
        fail ArgumentError, 'day_number cannot be nil'
      end

      if day_number > 7
        fail ArgumentError, 'invalid value for "day_number", must be smaller than or equal to 7.'
      end

      if day_number < 1
        fail ArgumentError, 'invalid value for "day_number", must be greater than or equal to 1.'
      end

      @day_number = day_number
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          unix == o.unix &&
          unix_ms == o.unix_ms &&
          utc == o.utc &&
          iso_local == o.iso_local &&
          rfc2822 == o.rfc2822 &&
          human == o.human &&
          day_number == o.day_number &&
          day_short == o.day_short &&
          day_full == o.day_full &&
          timezone == o.timezone &&
          formatted == o.formatted &&
          offset == o.offset &&
          dst == o.dst
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [unix, unix_ms, utc, iso_local, rfc2822, human, day_number, day_short, day_full, timezone, formatted, offset, dst].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TimeLogic::DirectApi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
