/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.timelogic.direct.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.timelogic.direct.api.models.ElapsedResponse

class ElapsedResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ElapsedResponse
        //val modelInstance = ElapsedResponse()

        // to test the property `seconds`
        should("test seconds") {
            // uncomment below to test the property
            //modelInstance.seconds shouldBe ("TODO")
        }

        // to test the property `minutes`
        should("test minutes") {
            // uncomment below to test the property
            //modelInstance.minutes shouldBe ("TODO")
        }

        // to test the property `hours`
        should("test hours") {
            // uncomment below to test the property
            //modelInstance.hours shouldBe ("TODO")
        }

        // to test the property `days`
        should("test days") {
            // uncomment below to test the property
            //modelInstance.days shouldBe ("TODO")
        }

        // to test the property `human`
        should("test human") {
            // uncomment below to test the property
            //modelInstance.human shouldBe ("TODO")
        }

        // to test the property `direction` - `left` means the target instant is still in the future. `passed` means the target instant is already in the past.
        should("test direction") {
            // uncomment below to test the property
            //modelInstance.direction shouldBe ("TODO")
        }

        // to test the property `formatted`
        should("test formatted") {
            // uncomment below to test the property
            //modelInstance.formatted shouldBe ("TODO")
        }

        // to test the property `businessDays`
        should("test businessDays") {
            // uncomment below to test the property
            //modelInstance.businessDays shouldBe ("TODO")
        }

    }
}
