/**
 *
 * Please note:
 * This class is auto generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.timelogic.direct.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.timelogic.direct.api.models.ErrorResponse
import com.timelogic.direct.api.models.ApiError

class ErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorResponse
        //val modelInstance = ErrorResponse()

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `requestId`
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `timestamp` - Intentionally omitted from public API error responses to avoid exposing request timing; use request_id for support correlation.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
