/**
 *
 * Please note:
 * This class is auto generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.timelogic.direct.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.timelogic.direct.api.models.TimePayloadBulkResponse
import com.timelogic.direct.api.models.TimePayloadBulkItem

class TimePayloadBulkResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimePayloadBulkResponse
        //val modelInstance = TimePayloadBulkResponse()

    }
}
