/* tslint:disable */
/* eslint-disable */
/**
 * TimeLogic API | A World Time API
 * Official public API contract for TimeLogic API.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - the API supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git).
 * https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     *
     * @type {string}
     * @memberof ApiError
     */
    code: ApiErrorCodeEnum;
    /**
     *
     * @type {string}
     * @memberof ApiError
     */
    message: string;
    /**
     * Optional implementation-specific detail payload.
     * @type {any}
     * @memberof ApiError
     */
    details?: any | null;
}


/**
 * @export
 */
export const ApiErrorCodeEnum = {
    AmbiguousTarget: 'AMBIGUOUS_TARGET',
    MissingTarget: 'MISSING_TARGET',
    InvalidParameter: 'INVALID_PARAMETER',
    InvalidTimestamp: 'INVALID_TIMESTAMP',
    DependencyNotReady: 'DEPENDENCY_NOT_READY',
    SigningNotReady: 'SIGNING_NOT_READY',
    Unauthorized: 'UNAUTHORIZED',
    InvalidAuth: 'INVALID_AUTH',
    MethodNotAllowed: 'METHOD_NOT_ALLOWED',
    NotFound: 'NOT_FOUND',
    InternalError: 'INTERNAL_ERROR',
    SubscriptionInactive: 'SUBSCRIPTION_INACTIVE',
    QuotaExceeded: 'QUOTA_EXCEEDED'
} as const;
export type ApiErrorCodeEnum = typeof ApiErrorCodeEnum[keyof typeof ApiErrorCodeEnum];


/**
 * Check if a given object implements the ApiError interface.
 */
export function instanceOfApiError(value: object): value is ApiError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ApiErrorFromJSON(json: any): ApiError {
    return ApiErrorFromJSONTyped(json, false);
}

export function ApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiError {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ApiErrorToJSON(json: any): ApiError {
    return ApiErrorToJSONTyped(json, false);
}

export function ApiErrorToJSONTyped(value?: ApiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
    };
}

