/* tslint:disable */
/* eslint-disable */
/**
 * TimeLogic API | A World Time API
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiffEndpointRef } from './DiffEndpointRef';
import {
    DiffEndpointRefFromJSON,
    DiffEndpointRefFromJSONTyped,
    DiffEndpointRefToJSON,
    DiffEndpointRefToJSONTyped,
} from './DiffEndpointRef';

/**
 * 
 * @export
 * @interface DiffResponse
 */
export interface DiffResponse {
    /**
     * 
     * @type {number}
     * @memberof DiffResponse
     */
    seconds: number;
    /**
     * 
     * @type {number}
     * @memberof DiffResponse
     */
    minutes: number;
    /**
     * 
     * @type {number}
     * @memberof DiffResponse
     */
    hours: number;
    /**
     * 
     * @type {number}
     * @memberof DiffResponse
     */
    days: number;
    /**
     * `forward` means `to` is after `from`. `backward` means `to` is before `from`. `same` means both sides resolve to the same instant.
     * @type {string}
     * @memberof DiffResponse
     */
    direction: DiffResponseDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof DiffResponse
     */
    human: string;
    /**
     * 
     * @type {string}
     * @memberof DiffResponse
     */
    formatted?: string;
    /**
     * 
     * @type {number}
     * @memberof DiffResponse
     */
    businessDays?: number;
    /**
     * 
     * @type {DiffEndpointRef}
     * @memberof DiffResponse
     */
    from: DiffEndpointRef;
    /**
     * 
     * @type {DiffEndpointRef}
     * @memberof DiffResponse
     */
    to: DiffEndpointRef;
}


/**
 * @export
 */
export const DiffResponseDirectionEnum = {
    Forward: 'forward',
    Backward: 'backward',
    Same: 'same'
} as const;
export type DiffResponseDirectionEnum = typeof DiffResponseDirectionEnum[keyof typeof DiffResponseDirectionEnum];


/**
 * Check if a given object implements the DiffResponse interface.
 */
export function instanceOfDiffResponse(value: object): value is DiffResponse {
    if (!('seconds' in value) || value['seconds'] === undefined) return false;
    if (!('minutes' in value) || value['minutes'] === undefined) return false;
    if (!('hours' in value) || value['hours'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('human' in value) || value['human'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function DiffResponseFromJSON(json: any): DiffResponse {
    return DiffResponseFromJSONTyped(json, false);
}

export function DiffResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiffResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'seconds': json['seconds'],
        'minutes': json['minutes'],
        'hours': json['hours'],
        'days': json['days'],
        'direction': json['direction'],
        'human': json['human'],
        'formatted': json['formatted'] == null ? undefined : json['formatted'],
        'businessDays': json['business_days'] == null ? undefined : json['business_days'],
        'from': DiffEndpointRefFromJSON(json['from']),
        'to': DiffEndpointRefFromJSON(json['to']),
    };
}

export function DiffResponseToJSON(json: any): DiffResponse {
    return DiffResponseToJSONTyped(json, false);
}

export function DiffResponseToJSONTyped(value?: DiffResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seconds': value['seconds'],
        'minutes': value['minutes'],
        'hours': value['hours'],
        'days': value['days'],
        'direction': value['direction'],
        'human': value['human'],
        'formatted': value['formatted'],
        'business_days': value['businessDays'],
        'from': DiffEndpointRefToJSON(value['from']),
        'to': DiffEndpointRefToJSON(value['to']),
    };
}

