/* tslint:disable */
/* eslint-disable */
/**
 * TimeLogic API | A World Time API
 * Official public API contract for TimeLogic API.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - the API supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git).
 * https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
 * Do not edit the class manually.
 */

import type { TimePayload } from './TimePayload';
import {
    instanceOfTimePayload,
    TimePayloadFromJSON,
    TimePayloadFromJSONTyped,
    TimePayloadToJSON,
} from './TimePayload';
import type { TimePayloadBulkResponse } from './TimePayloadBulkResponse';
import {
    instanceOfTimePayloadBulkResponse,
    TimePayloadBulkResponseFromJSON,
    TimePayloadBulkResponseFromJSONTyped,
    TimePayloadBulkResponseToJSON,
} from './TimePayloadBulkResponse';

/**
 * @type GetCurrentTime200Response
 *
 * @export
 */
export type GetCurrentTime200Response = TimePayload | TimePayloadBulkResponse;

export function GetCurrentTime200ResponseFromJSON(json: any): GetCurrentTime200Response {
    return GetCurrentTime200ResponseFromJSONTyped(json, false);
}

export function GetCurrentTime200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentTime200Response {
    if (json == null) {
        return json;
    }
    if (instanceOfTimePayload(json)) {
        return TimePayloadFromJSONTyped(json, true);
    }
    if (instanceOfTimePayloadBulkResponse(json)) {
        return TimePayloadBulkResponseFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetCurrentTime200ResponseToJSON(json: any): any {
    return GetCurrentTime200ResponseToJSONTyped(json, false);
}

export function GetCurrentTime200ResponseToJSONTyped(value?: GetCurrentTime200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTimePayload(value)) {
        return TimePayloadToJSON(value as TimePayload);
    }
    if (instanceOfTimePayloadBulkResponse(value)) {
        return TimePayloadBulkResponseToJSON(value as TimePayloadBulkResponse);
    }

    return {};
}

