/* tslint:disable */
/* eslint-disable */
/**
 * TimeLogic API | A World Time API
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimezoneOffsetResponse } from './TimezoneOffsetResponse';
import {
    instanceOfTimezoneOffsetResponse,
    TimezoneOffsetResponseFromJSON,
    TimezoneOffsetResponseFromJSONTyped,
    TimezoneOffsetResponseToJSON,
} from './TimezoneOffsetResponse';
import type { TimezoneResolvedResponse } from './TimezoneResolvedResponse';
import {
    instanceOfTimezoneResolvedResponse,
    TimezoneResolvedResponseFromJSON,
    TimezoneResolvedResponseFromJSONTyped,
    TimezoneResolvedResponseToJSON,
} from './TimezoneResolvedResponse';

/**
 * @type GetTimezone200Response
 * 
 * @export
 */
export type GetTimezone200Response = TimezoneOffsetResponse | TimezoneResolvedResponse;

export function GetTimezone200ResponseFromJSON(json: any): GetTimezone200Response {
    return GetTimezone200ResponseFromJSONTyped(json, false);
}

export function GetTimezone200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimezone200Response {
    if (json == null) {
        return json;
    }
    if (instanceOfTimezoneOffsetResponse(json)) {
        return TimezoneOffsetResponseFromJSONTyped(json, true);
    }
    if (instanceOfTimezoneResolvedResponse(json)) {
        return TimezoneResolvedResponseFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetTimezone200ResponseToJSON(json: any): any {
    return GetTimezone200ResponseToJSONTyped(json, false);
}

export function GetTimezone200ResponseToJSONTyped(value?: GetTimezone200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTimezoneOffsetResponse(value)) {
        return TimezoneOffsetResponseToJSON(value as TimezoneOffsetResponse);
    }
    if (instanceOfTimezoneResolvedResponse(value)) {
        return TimezoneResolvedResponseToJSON(value as TimezoneResolvedResponse);
    }

    return {};
}

