/* tslint:disable */
/* eslint-disable */
/**
 * TimeLogic API | A World Time API
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimePayloadBulkItem } from './TimePayloadBulkItem';
import {
    TimePayloadBulkItemFromJSON,
    TimePayloadBulkItemFromJSONTyped,
    TimePayloadBulkItemToJSON,
    TimePayloadBulkItemToJSONTyped,
} from './TimePayloadBulkItem';

/**
 * Bulk response array returned when `/v1/time/current` or `/v1/time/convert` receives one comma-separated `tz`, `ip`, or `offset` selector.
 * @export
 * @interface TimePayloadBulkResponse
 */
export interface TimePayloadBulkResponse extends Array<TimePayloadBulkItem> {
}

/**
 * Check if a given object implements the TimePayloadBulkResponse interface.
 */
export function instanceOfTimePayloadBulkResponse(value: object): value is TimePayloadBulkResponse {
    return true;
}

export function TimePayloadBulkResponseFromJSON(json: any): TimePayloadBulkResponse {
    return TimePayloadBulkResponseFromJSONTyped(json, false);
}

export function TimePayloadBulkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimePayloadBulkResponse {
    return json;
}

export function TimePayloadBulkResponseToJSON(json: any): TimePayloadBulkResponse {
    return TimePayloadBulkResponseToJSONTyped(json, false);
}

export function TimePayloadBulkResponseToJSONTyped(value?: TimePayloadBulkResponse | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

