/* tslint:disable */
/* eslint-disable */
/**
 * TimeLogic API | A World Time API
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimezoneMatch
 */
export interface TimezoneMatch {
    /**
     * 
     * @type {number}
     * @memberof TimezoneMatch
     */
    unix: number;
    /**
     * 
     * @type {number}
     * @memberof TimezoneMatch
     */
    unixMs: number;
    /**
     * 
     * @type {Date}
     * @memberof TimezoneMatch
     */
    utc: Date;
    /**
     * 
     * @type {string}
     * @memberof TimezoneMatch
     */
    isoLocal: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimezoneMatch
     */
    rfc2822: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneMatch
     */
    human: string;
    /**
     * 
     * @type {number}
     * @memberof TimezoneMatch
     */
    dayNumber: number;
    /**
     * 
     * @type {string}
     * @memberof TimezoneMatch
     */
    dayShort: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneMatch
     */
    dayFull: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneMatch
     */
    timezone: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneMatch
     */
    formatted?: string;
    /**
     * 
     * @type {number}
     * @memberof TimezoneMatch
     */
    offset: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimezoneMatch
     */
    dst: boolean;
}

/**
 * Check if a given object implements the TimezoneMatch interface.
 */
export function instanceOfTimezoneMatch(value: object): value is TimezoneMatch {
    if (!('unix' in value) || value['unix'] === undefined) return false;
    if (!('unixMs' in value) || value['unixMs'] === undefined) return false;
    if (!('utc' in value) || value['utc'] === undefined) return false;
    if (!('isoLocal' in value) || value['isoLocal'] === undefined) return false;
    if (!('rfc2822' in value) || value['rfc2822'] === undefined) return false;
    if (!('human' in value) || value['human'] === undefined) return false;
    if (!('dayNumber' in value) || value['dayNumber'] === undefined) return false;
    if (!('dayShort' in value) || value['dayShort'] === undefined) return false;
    if (!('dayFull' in value) || value['dayFull'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('dst' in value) || value['dst'] === undefined) return false;
    return true;
}

export function TimezoneMatchFromJSON(json: any): TimezoneMatch {
    return TimezoneMatchFromJSONTyped(json, false);
}

export function TimezoneMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimezoneMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'unix': json['unix'],
        'unixMs': json['unix_ms'],
        'utc': (new Date(json['utc'])),
        'isoLocal': json['iso_local'],
        'rfc2822': json['rfc2822'],
        'human': json['human'],
        'dayNumber': json['day_number'],
        'dayShort': json['day_short'],
        'dayFull': json['day_full'],
        'timezone': json['timezone'],
        'formatted': json['formatted'] == null ? undefined : json['formatted'],
        'offset': json['offset'],
        'dst': json['dst'],
    };
}

export function TimezoneMatchToJSON(json: any): TimezoneMatch {
    return TimezoneMatchToJSONTyped(json, false);
}

export function TimezoneMatchToJSONTyped(value?: TimezoneMatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unix': value['unix'],
        'unix_ms': value['unixMs'],
        'utc': ((value['utc']).toISOString()),
        'iso_local': value['isoLocal'],
        'rfc2822': value['rfc2822'],
        'human': value['human'],
        'day_number': value['dayNumber'],
        'day_short': value['dayShort'],
        'day_full': value['dayFull'],
        'timezone': value['timezone'],
        'formatted': value['formatted'],
        'offset': value['offset'],
        'dst': value['dst'],
    };
}

