/*
 * TimeLogic API — Direct Customer Access
 *
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TimeLogic.DirectApi.Client;
using TimeLogic.DirectApi.Api;
// uncomment below to import models
//using TimeLogic.DirectApi.Model;

namespace TimeLogic.DirectApi.Test.Api
{
    /// <summary>
    ///  Class for testing UtilityApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UtilityApiTests : IDisposable
    {
        private UtilityApi instance;

        public UtilityApiTests()
        {
            instance = new UtilityApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UtilityApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UtilityApi
            //Assert.IsType<UtilityApi>(instance);
        }

        /// <summary>
        /// Test GetPublicSigningKey
        /// </summary>
        [Fact]
        public void GetPublicSigningKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? kid = null;
            //var response = instance.GetPublicSigningKey(kid);
            //Assert.IsType<JwksResponse>(response);
        }
    }
}
