/*
 * TimeLogic API — Direct Customer Access
 *
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TimeLogic.DirectApi.Client.OpenAPIDateConverter;

namespace TimeLogic.DirectApi.Model
{
    /// <summary>
    /// DiffResponse
    /// </summary>
    [DataContract(Name = "DiffResponse")]
    public partial class DiffResponse : IValidatableObject
    {
        /// <summary>
        /// &#x60;forward&#x60; means &#x60;to&#x60; is after &#x60;from&#x60;. &#x60;backward&#x60; means &#x60;to&#x60; is before &#x60;from&#x60;. &#x60;same&#x60; means both sides resolve to the same instant.
        /// </summary>
        /// <value>&#x60;forward&#x60; means &#x60;to&#x60; is after &#x60;from&#x60;. &#x60;backward&#x60; means &#x60;to&#x60; is before &#x60;from&#x60;. &#x60;same&#x60; means both sides resolve to the same instant.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DirectionEnum
        {
            /// <summary>
            /// Enum Forward for value: forward
            /// </summary>
            [EnumMember(Value = "forward")]
            Forward = 1,

            /// <summary>
            /// Enum Backward for value: backward
            /// </summary>
            [EnumMember(Value = "backward")]
            Backward = 2,

            /// <summary>
            /// Enum Same for value: same
            /// </summary>
            [EnumMember(Value = "same")]
            Same = 3
        }


        /// <summary>
        /// &#x60;forward&#x60; means &#x60;to&#x60; is after &#x60;from&#x60;. &#x60;backward&#x60; means &#x60;to&#x60; is before &#x60;from&#x60;. &#x60;same&#x60; means both sides resolve to the same instant.
        /// </summary>
        /// <value>&#x60;forward&#x60; means &#x60;to&#x60; is after &#x60;from&#x60;. &#x60;backward&#x60; means &#x60;to&#x60; is before &#x60;from&#x60;. &#x60;same&#x60; means both sides resolve to the same instant.</value>
        [DataMember(Name = "direction", IsRequired = true, EmitDefaultValue = true)]
        public DirectionEnum Direction { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DiffResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DiffResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DiffResponse" /> class.
        /// </summary>
        /// <param name="seconds">seconds (required).</param>
        /// <param name="minutes">minutes (required).</param>
        /// <param name="hours">hours (required).</param>
        /// <param name="days">days (required).</param>
        /// <param name="direction">&#x60;forward&#x60; means &#x60;to&#x60; is after &#x60;from&#x60;. &#x60;backward&#x60; means &#x60;to&#x60; is before &#x60;from&#x60;. &#x60;same&#x60; means both sides resolve to the same instant. (required).</param>
        /// <param name="human">human (required).</param>
        /// <param name="formatted">formatted.</param>
        /// <param name="businessDays">businessDays.</param>
        /// <param name="from">from (required).</param>
        /// <param name="to">to (required).</param>
        public DiffResponse(int seconds = default(int), int minutes = default(int), int hours = default(int), int days = default(int), DirectionEnum direction = default(DirectionEnum), string human = default(string), string formatted = default(string), int businessDays = default(int), DiffEndpointRef from = default(DiffEndpointRef), DiffEndpointRef to = default(DiffEndpointRef))
        {
            this.Seconds = seconds;
            this.Minutes = minutes;
            this.Hours = hours;
            this.Days = days;
            this.Direction = direction;
            // to ensure "human" is required (not null)
            if (human == null)
            {
                throw new ArgumentNullException("human is a required property for DiffResponse and cannot be null");
            }
            this.Human = human;
            // to ensure "from" is required (not null)
            if (from == null)
            {
                throw new ArgumentNullException("from is a required property for DiffResponse and cannot be null");
            }
            this.From = from;
            // to ensure "to" is required (not null)
            if (to == null)
            {
                throw new ArgumentNullException("to is a required property for DiffResponse and cannot be null");
            }
            this.To = to;
            this.Formatted = formatted;
            this.BusinessDays = businessDays;
        }

        /// <summary>
        /// Gets or Sets Seconds
        /// </summary>
        [DataMember(Name = "seconds", IsRequired = true, EmitDefaultValue = true)]
        public int Seconds { get; set; }

        /// <summary>
        /// Gets or Sets Minutes
        /// </summary>
        [DataMember(Name = "minutes", IsRequired = true, EmitDefaultValue = true)]
        public int Minutes { get; set; }

        /// <summary>
        /// Gets or Sets Hours
        /// </summary>
        [DataMember(Name = "hours", IsRequired = true, EmitDefaultValue = true)]
        public int Hours { get; set; }

        /// <summary>
        /// Gets or Sets Days
        /// </summary>
        [DataMember(Name = "days", IsRequired = true, EmitDefaultValue = true)]
        public int Days { get; set; }

        /// <summary>
        /// Gets or Sets Human
        /// </summary>
        [DataMember(Name = "human", IsRequired = true, EmitDefaultValue = true)]
        public string Human { get; set; }

        /// <summary>
        /// Gets or Sets Formatted
        /// </summary>
        [DataMember(Name = "formatted", EmitDefaultValue = false)]
        public string Formatted { get; set; }

        /// <summary>
        /// Gets or Sets BusinessDays
        /// </summary>
        [DataMember(Name = "business_days", EmitDefaultValue = false)]
        public int BusinessDays { get; set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        [DataMember(Name = "from", IsRequired = true, EmitDefaultValue = true)]
        public DiffEndpointRef From { get; set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [DataMember(Name = "to", IsRequired = true, EmitDefaultValue = true)]
        public DiffEndpointRef To { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DiffResponse {\n");
            sb.Append("  Seconds: ").Append(Seconds).Append("\n");
            sb.Append("  Minutes: ").Append(Minutes).Append("\n");
            sb.Append("  Hours: ").Append(Hours).Append("\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  Human: ").Append(Human).Append("\n");
            sb.Append("  Formatted: ").Append(Formatted).Append("\n");
            sb.Append("  BusinessDays: ").Append(BusinessDays).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
