/*
 * TimeLogic API — Direct Customer Access
 *
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TimeLogic.DirectApi.Client.OpenAPIDateConverter;

namespace TimeLogic.DirectApi.Model
{
    /// <summary>
    /// Offset-based timezone lookup result with &#x60;matching_zones&#x60; for the current request-time offset match.
    /// </summary>
    [DataContract(Name = "TimezoneOffsetResponse")]
    public partial class TimezoneOffsetResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimezoneOffsetResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TimezoneOffsetResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TimezoneOffsetResponse" /> class.
        /// </summary>
        /// <param name="unix">unix (required).</param>
        /// <param name="unixMs">unixMs (required).</param>
        /// <param name="utc">utc (required).</param>
        /// <param name="isoLocal">isoLocal (required).</param>
        /// <param name="rfc2822">rfc2822 (required).</param>
        /// <param name="human">human (required).</param>
        /// <param name="dayNumber">dayNumber (required).</param>
        /// <param name="dayShort">dayShort (required).</param>
        /// <param name="dayFull">dayFull (required).</param>
        /// <param name="timezone">timezone (required).</param>
        /// <param name="formatted">formatted.</param>
        /// <param name="offset">offset (required).</param>
        /// <param name="dst">dst (required).</param>
        /// <param name="matchingZones">matchingZones (required).</param>
        public TimezoneOffsetResponse(long unix = default(long), long unixMs = default(long), DateTime utc = default(DateTime), string isoLocal = default(string), string rfc2822 = default(string), string human = default(string), int dayNumber = default(int), string dayShort = default(string), string dayFull = default(string), string timezone = default(string), string formatted = default(string), int offset = default(int), bool dst = default(bool), List<TimezoneMatch> matchingZones = default(List<TimezoneMatch>))
        {
            this.Unix = unix;
            this.UnixMs = unixMs;
            this.Utc = utc;
            // to ensure "isoLocal" is required (not null)
            if (isoLocal == null)
            {
                throw new ArgumentNullException("isoLocal is a required property for TimezoneOffsetResponse and cannot be null");
            }
            this.IsoLocal = isoLocal;
            // to ensure "rfc2822" is required (not null)
            if (rfc2822 == null)
            {
                throw new ArgumentNullException("rfc2822 is a required property for TimezoneOffsetResponse and cannot be null");
            }
            this.Rfc2822 = rfc2822;
            // to ensure "human" is required (not null)
            if (human == null)
            {
                throw new ArgumentNullException("human is a required property for TimezoneOffsetResponse and cannot be null");
            }
            this.Human = human;
            this.DayNumber = dayNumber;
            // to ensure "dayShort" is required (not null)
            if (dayShort == null)
            {
                throw new ArgumentNullException("dayShort is a required property for TimezoneOffsetResponse and cannot be null");
            }
            this.DayShort = dayShort;
            // to ensure "dayFull" is required (not null)
            if (dayFull == null)
            {
                throw new ArgumentNullException("dayFull is a required property for TimezoneOffsetResponse and cannot be null");
            }
            this.DayFull = dayFull;
            // to ensure "timezone" is required (not null)
            if (timezone == null)
            {
                throw new ArgumentNullException("timezone is a required property for TimezoneOffsetResponse and cannot be null");
            }
            this.Timezone = timezone;
            this.Offset = offset;
            this.Dst = dst;
            // to ensure "matchingZones" is required (not null)
            if (matchingZones == null)
            {
                throw new ArgumentNullException("matchingZones is a required property for TimezoneOffsetResponse and cannot be null");
            }
            this.MatchingZones = matchingZones;
            this.Formatted = formatted;
        }

        /// <summary>
        /// Gets or Sets Unix
        /// </summary>
        [DataMember(Name = "unix", IsRequired = true, EmitDefaultValue = true)]
        public long Unix { get; set; }

        /// <summary>
        /// Gets or Sets UnixMs
        /// </summary>
        [DataMember(Name = "unix_ms", IsRequired = true, EmitDefaultValue = true)]
        public long UnixMs { get; set; }

        /// <summary>
        /// Gets or Sets Utc
        /// </summary>
        [DataMember(Name = "utc", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Utc { get; set; }

        /// <summary>
        /// Gets or Sets IsoLocal
        /// </summary>
        [DataMember(Name = "iso_local", IsRequired = true, EmitDefaultValue = true)]
        public string IsoLocal { get; set; }

        /// <summary>
        /// Gets or Sets Rfc2822
        /// </summary>
        [DataMember(Name = "rfc2822", IsRequired = true, EmitDefaultValue = true)]
        public string Rfc2822 { get; set; }

        /// <summary>
        /// Gets or Sets Human
        /// </summary>
        [DataMember(Name = "human", IsRequired = true, EmitDefaultValue = true)]
        public string Human { get; set; }

        /// <summary>
        /// Gets or Sets DayNumber
        /// </summary>
        [DataMember(Name = "day_number", IsRequired = true, EmitDefaultValue = true)]
        public int DayNumber { get; set; }

        /// <summary>
        /// Gets or Sets DayShort
        /// </summary>
        [DataMember(Name = "day_short", IsRequired = true, EmitDefaultValue = true)]
        public string DayShort { get; set; }

        /// <summary>
        /// Gets or Sets DayFull
        /// </summary>
        [DataMember(Name = "day_full", IsRequired = true, EmitDefaultValue = true)]
        public string DayFull { get; set; }

        /// <summary>
        /// Gets or Sets Timezone
        /// </summary>
        [DataMember(Name = "timezone", IsRequired = true, EmitDefaultValue = true)]
        public string Timezone { get; set; }

        /// <summary>
        /// Gets or Sets Formatted
        /// </summary>
        [DataMember(Name = "formatted", EmitDefaultValue = false)]
        public string Formatted { get; set; }

        /// <summary>
        /// Gets or Sets Offset
        /// </summary>
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public int Offset { get; set; }

        /// <summary>
        /// Gets or Sets Dst
        /// </summary>
        [DataMember(Name = "dst", IsRequired = true, EmitDefaultValue = true)]
        public bool Dst { get; set; }

        /// <summary>
        /// Gets or Sets MatchingZones
        /// </summary>
        [DataMember(Name = "matching_zones", IsRequired = true, EmitDefaultValue = true)]
        public List<TimezoneMatch> MatchingZones { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TimezoneOffsetResponse {\n");
            sb.Append("  Unix: ").Append(Unix).Append("\n");
            sb.Append("  UnixMs: ").Append(UnixMs).Append("\n");
            sb.Append("  Utc: ").Append(Utc).Append("\n");
            sb.Append("  IsoLocal: ").Append(IsoLocal).Append("\n");
            sb.Append("  Rfc2822: ").Append(Rfc2822).Append("\n");
            sb.Append("  Human: ").Append(Human).Append("\n");
            sb.Append("  DayNumber: ").Append(DayNumber).Append("\n");
            sb.Append("  DayShort: ").Append(DayShort).Append("\n");
            sb.Append("  DayFull: ").Append(DayFull).Append("\n");
            sb.Append("  Timezone: ").Append(Timezone).Append("\n");
            sb.Append("  Formatted: ").Append(Formatted).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  Dst: ").Append(Dst).Append("\n");
            sb.Append("  MatchingZones: ").Append(MatchingZones).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DayNumber (int) maximum
            if (this.DayNumber > (int)7)
            {
                yield return new ValidationResult("Invalid value for DayNumber, must be a value less than or equal to 7.", new [] { "DayNumber" });
            }

            // DayNumber (int) minimum
            if (this.DayNumber < (int)1)
            {
                yield return new ValidationResult("Invalid value for DayNumber, must be a value greater than or equal to 1.", new [] { "DayNumber" });
            }

            yield break;
        }
    }

}
