/*
 * TimeLogic API | A World Time API
 *
 * Official public API contract for TimeLogic API.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - the API supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TimeLogic.Api.Client.OpenAPIDateConverter;

namespace TimeLogic.Api.Model
{
    /// <summary>
    /// ApiError
    /// </summary>
    [DataContract(Name = "ApiError")]
    public partial class ApiError : IValidatableObject
    {
        /// <summary>
        /// Defines Code
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum AMBIGUOUSTARGET for value: AMBIGUOUS_TARGET
            /// </summary>
            [EnumMember(Value = "AMBIGUOUS_TARGET")]
            AMBIGUOUSTARGET = 1,

            /// <summary>
            /// Enum MISSINGTARGET for value: MISSING_TARGET
            /// </summary>
            [EnumMember(Value = "MISSING_TARGET")]
            MISSINGTARGET = 2,

            /// <summary>
            /// Enum INVALIDPARAMETER for value: INVALID_PARAMETER
            /// </summary>
            [EnumMember(Value = "INVALID_PARAMETER")]
            INVALIDPARAMETER = 3,

            /// <summary>
            /// Enum INVALIDTIMESTAMP for value: INVALID_TIMESTAMP
            /// </summary>
            [EnumMember(Value = "INVALID_TIMESTAMP")]
            INVALIDTIMESTAMP = 4,

            /// <summary>
            /// Enum DEPENDENCYNOTREADY for value: DEPENDENCY_NOT_READY
            /// </summary>
            [EnumMember(Value = "DEPENDENCY_NOT_READY")]
            DEPENDENCYNOTREADY = 5,

            /// <summary>
            /// Enum SIGNINGNOTREADY for value: SIGNING_NOT_READY
            /// </summary>
            [EnumMember(Value = "SIGNING_NOT_READY")]
            SIGNINGNOTREADY = 6,

            /// <summary>
            /// Enum UNAUTHORIZED for value: UNAUTHORIZED
            /// </summary>
            [EnumMember(Value = "UNAUTHORIZED")]
            UNAUTHORIZED = 7,

            /// <summary>
            /// Enum INVALIDAUTH for value: INVALID_AUTH
            /// </summary>
            [EnumMember(Value = "INVALID_AUTH")]
            INVALIDAUTH = 8,

            /// <summary>
            /// Enum METHODNOTALLOWED for value: METHOD_NOT_ALLOWED
            /// </summary>
            [EnumMember(Value = "METHOD_NOT_ALLOWED")]
            METHODNOTALLOWED = 9,

            /// <summary>
            /// Enum NOTFOUND for value: NOT_FOUND
            /// </summary>
            [EnumMember(Value = "NOT_FOUND")]
            NOTFOUND = 10,

            /// <summary>
            /// Enum INTERNALERROR for value: INTERNAL_ERROR
            /// </summary>
            [EnumMember(Value = "INTERNAL_ERROR")]
            INTERNALERROR = 11,

            /// <summary>
            /// Enum SUBSCRIPTIONINACTIVE for value: SUBSCRIPTION_INACTIVE
            /// </summary>
            [EnumMember(Value = "SUBSCRIPTION_INACTIVE")]
            SUBSCRIPTIONINACTIVE = 12,

            /// <summary>
            /// Enum QUOTAEXCEEDED for value: QUOTA_EXCEEDED
            /// </summary>
            [EnumMember(Value = "QUOTA_EXCEEDED")]
            QUOTAEXCEEDED = 13
        }


        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiError" /> class.
        /// </summary>
        /// <param name="code">code (required).</param>
        /// <param name="message">message (required).</param>
        /// <param name="details">Optional implementation-specific detail payload..</param>
        public ApiError(CodeEnum code = default(CodeEnum), string message = default(string), Object details = default(Object))
        {
            this.Code = code;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for ApiError and cannot be null");
            }
            this.Message = message;
            this.Details = details;
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Optional implementation-specific detail payload.
        /// </summary>
        /// <value>Optional implementation-specific detail payload.</value>
        [DataMember(Name = "details", EmitDefaultValue = true)]
        public Object Details { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
