/*
 * TimeLogic API | A World Time API
 *
 * Official public API contract for TimeLogic API.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - the API supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TimeLogic.Api.Client.OpenAPIDateConverter;

namespace TimeLogic.Api.Model
{
    /// <summary>
    /// ElapsedResponse
    /// </summary>
    [DataContract(Name = "ElapsedResponse")]
    public partial class ElapsedResponse : IValidatableObject
    {
        /// <summary>
        /// &#x60;left&#x60; means the target instant is still in the future. &#x60;passed&#x60; means the target instant is already in the past.
        /// </summary>
        /// <value>&#x60;left&#x60; means the target instant is still in the future. &#x60;passed&#x60; means the target instant is already in the past.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DirectionEnum
        {
            /// <summary>
            /// Enum Left for value: left
            /// </summary>
            [EnumMember(Value = "left")]
            Left = 1,

            /// <summary>
            /// Enum Passed for value: passed
            /// </summary>
            [EnumMember(Value = "passed")]
            Passed = 2
        }


        /// <summary>
        /// &#x60;left&#x60; means the target instant is still in the future. &#x60;passed&#x60; means the target instant is already in the past.
        /// </summary>
        /// <value>&#x60;left&#x60; means the target instant is still in the future. &#x60;passed&#x60; means the target instant is already in the past.</value>
        [DataMember(Name = "direction", IsRequired = true, EmitDefaultValue = true)]
        public DirectionEnum Direction { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ElapsedResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ElapsedResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ElapsedResponse" /> class.
        /// </summary>
        /// <param name="seconds">seconds (required).</param>
        /// <param name="minutes">minutes (required).</param>
        /// <param name="hours">hours (required).</param>
        /// <param name="days">days (required).</param>
        /// <param name="human">human (required).</param>
        /// <param name="direction">&#x60;left&#x60; means the target instant is still in the future. &#x60;passed&#x60; means the target instant is already in the past. (required).</param>
        /// <param name="formatted">formatted.</param>
        /// <param name="businessDays">businessDays.</param>
        public ElapsedResponse(int seconds = default(int), int minutes = default(int), int hours = default(int), int days = default(int), string human = default(string), DirectionEnum direction = default(DirectionEnum), string formatted = default(string), int businessDays = default(int))
        {
            this.Seconds = seconds;
            this.Minutes = minutes;
            this.Hours = hours;
            this.Days = days;
            // to ensure "human" is required (not null)
            if (human == null)
            {
                throw new ArgumentNullException("human is a required property for ElapsedResponse and cannot be null");
            }
            this.Human = human;
            this.Direction = direction;
            this.Formatted = formatted;
            this.BusinessDays = businessDays;
        }

        /// <summary>
        /// Gets or Sets Seconds
        /// </summary>
        [DataMember(Name = "seconds", IsRequired = true, EmitDefaultValue = true)]
        public int Seconds { get; set; }

        /// <summary>
        /// Gets or Sets Minutes
        /// </summary>
        [DataMember(Name = "minutes", IsRequired = true, EmitDefaultValue = true)]
        public int Minutes { get; set; }

        /// <summary>
        /// Gets or Sets Hours
        /// </summary>
        [DataMember(Name = "hours", IsRequired = true, EmitDefaultValue = true)]
        public int Hours { get; set; }

        /// <summary>
        /// Gets or Sets Days
        /// </summary>
        [DataMember(Name = "days", IsRequired = true, EmitDefaultValue = true)]
        public int Days { get; set; }

        /// <summary>
        /// Gets or Sets Human
        /// </summary>
        [DataMember(Name = "human", IsRequired = true, EmitDefaultValue = true)]
        public string Human { get; set; }

        /// <summary>
        /// Gets or Sets Formatted
        /// </summary>
        [DataMember(Name = "formatted", EmitDefaultValue = false)]
        public string Formatted { get; set; }

        /// <summary>
        /// Gets or Sets BusinessDays
        /// </summary>
        [DataMember(Name = "business_days", EmitDefaultValue = false)]
        public int BusinessDays { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ElapsedResponse {\n");
            sb.Append("  Seconds: ").Append(Seconds).Append("\n");
            sb.Append("  Minutes: ").Append(Minutes).Append("\n");
            sb.Append("  Hours: ").Append(Hours).Append("\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  Human: ").Append(Human).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  Formatted: ").Append(Formatted).Append("\n");
            sb.Append("  BusinessDays: ").Append(BusinessDays).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
