/*
 * TimeLogic API | A World Time API
 *
 * Official public API contract for TimeLogic API.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - the API supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TimeLogic.Api.Client.OpenAPIDateConverter;
using System.Reflection;

namespace TimeLogic.Api.Model
{
    /// <summary>
    /// GetCurrentTime200Response
    /// </summary>
    [JsonConverter(typeof(GetCurrentTime200ResponseJsonConverter))]
    [DataContract(Name = "getCurrentTime_200_response")]
    public partial class GetCurrentTime200Response : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCurrentTime200Response" /> class
        /// with the <see cref="TimePayload" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TimePayload.</param>
        public GetCurrentTime200Response(TimePayload actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetCurrentTime200Response" /> class
        /// with the <see cref="TimePayloadBulkResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TimePayloadBulkResponse.</param>
        public GetCurrentTime200Response(TimePayloadBulkResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(TimePayload) || value is TimePayload)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TimePayloadBulkResponse) || value is TimePayloadBulkResponse)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: TimePayload, TimePayloadBulkResponse");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `TimePayload`. If the actual instance is not `TimePayload`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TimePayload</returns>
        public TimePayload GetTimePayload()
        {
            return (TimePayload)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TimePayloadBulkResponse`. If the actual instance is not `TimePayloadBulkResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TimePayloadBulkResponse</returns>
        public TimePayloadBulkResponse GetTimePayloadBulkResponse()
        {
            return (TimePayloadBulkResponse)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCurrentTime200Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, GetCurrentTime200Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of GetCurrentTime200Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of GetCurrentTime200Response</returns>
        public static GetCurrentTime200Response FromJson(string jsonString)
        {
            GetCurrentTime200Response newGetCurrentTime200Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newGetCurrentTime200Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TimePayload).GetProperty("AdditionalProperties") == null)
                {
                    newGetCurrentTime200Response = new GetCurrentTime200Response(JsonConvert.DeserializeObject<TimePayload>(jsonString, GetCurrentTime200Response.SerializerSettings));
                }
                else
                {
                    newGetCurrentTime200Response = new GetCurrentTime200Response(JsonConvert.DeserializeObject<TimePayload>(jsonString, GetCurrentTime200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TimePayload");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TimePayload: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TimePayloadBulkResponse).GetProperty("AdditionalProperties") == null)
                {
                    newGetCurrentTime200Response = new GetCurrentTime200Response(JsonConvert.DeserializeObject<TimePayloadBulkResponse>(jsonString, GetCurrentTime200Response.SerializerSettings));
                }
                else
                {
                    newGetCurrentTime200Response = new GetCurrentTime200Response(JsonConvert.DeserializeObject<TimePayloadBulkResponse>(jsonString, GetCurrentTime200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TimePayloadBulkResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TimePayloadBulkResponse: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newGetCurrentTime200Response;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for GetCurrentTime200Response
    /// </summary>
    public class GetCurrentTime200ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(GetCurrentTime200Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType)
            {
                case JsonToken.StartObject:
                    return GetCurrentTime200Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return GetCurrentTime200Response.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
