<?php
/**
 * TimezoneMatch
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  TimeLogic\DirectApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TimeLogic API — Direct Customer Access
 *
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TimeLogic\DirectApi\Model;

use \ArrayAccess;
use \TimeLogic\DirectApi\ObjectSerializer;

/**
 * TimezoneMatch Class Doc Comment
 *
 * @category Class
 * @package  TimeLogic\DirectApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TimezoneMatch implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TimezoneMatch';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'unix' => 'int',
        'unixMs' => 'int',
        'utc' => '\DateTime',
        'isoLocal' => 'string',
        'rfc2822' => 'string',
        'human' => 'string',
        'dayNumber' => 'int',
        'dayShort' => 'string',
        'dayFull' => 'string',
        'timezone' => 'string',
        'formatted' => 'string',
        'offset' => 'int',
        'dst' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'unix' => 'int64',
        'unixMs' => 'int64',
        'utc' => 'date-time',
        'isoLocal' => null,
        'rfc2822' => null,
        'human' => null,
        'dayNumber' => null,
        'dayShort' => null,
        'dayFull' => null,
        'timezone' => null,
        'formatted' => null,
        'offset' => null,
        'dst' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'unix' => false,
        'unixMs' => false,
        'utc' => false,
        'isoLocal' => true,
        'rfc2822' => false,
        'human' => false,
        'dayNumber' => false,
        'dayShort' => false,
        'dayFull' => false,
        'timezone' => false,
        'formatted' => false,
        'offset' => false,
        'dst' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'unix' => 'unix',
        'unixMs' => 'unix_ms',
        'utc' => 'utc',
        'isoLocal' => 'iso_local',
        'rfc2822' => 'rfc2822',
        'human' => 'human',
        'dayNumber' => 'day_number',
        'dayShort' => 'day_short',
        'dayFull' => 'day_full',
        'timezone' => 'timezone',
        'formatted' => 'formatted',
        'offset' => 'offset',
        'dst' => 'dst'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'unix' => 'setUnix',
        'unixMs' => 'setUnixMs',
        'utc' => 'setUtc',
        'isoLocal' => 'setIsoLocal',
        'rfc2822' => 'setRfc2822',
        'human' => 'setHuman',
        'dayNumber' => 'setDayNumber',
        'dayShort' => 'setDayShort',
        'dayFull' => 'setDayFull',
        'timezone' => 'setTimezone',
        'formatted' => 'setFormatted',
        'offset' => 'setOffset',
        'dst' => 'setDst'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'unix' => 'getUnix',
        'unixMs' => 'getUnixMs',
        'utc' => 'getUtc',
        'isoLocal' => 'getIsoLocal',
        'rfc2822' => 'getRfc2822',
        'human' => 'getHuman',
        'dayNumber' => 'getDayNumber',
        'dayShort' => 'getDayShort',
        'dayFull' => 'getDayFull',
        'timezone' => 'getTimezone',
        'formatted' => 'getFormatted',
        'offset' => 'getOffset',
        'dst' => 'getDst'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('unix', $data ?? [], null);
        $this->setIfExists('unixMs', $data ?? [], null);
        $this->setIfExists('utc', $data ?? [], null);
        $this->setIfExists('isoLocal', $data ?? [], null);
        $this->setIfExists('rfc2822', $data ?? [], null);
        $this->setIfExists('human', $data ?? [], null);
        $this->setIfExists('dayNumber', $data ?? [], null);
        $this->setIfExists('dayShort', $data ?? [], null);
        $this->setIfExists('dayFull', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('formatted', $data ?? [], null);
        $this->setIfExists('offset', $data ?? [], null);
        $this->setIfExists('dst', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['unix'] === null) {
            $invalidProperties[] = "'unix' can't be null";
        }
        if ($this->container['unixMs'] === null) {
            $invalidProperties[] = "'unixMs' can't be null";
        }
        if ($this->container['utc'] === null) {
            $invalidProperties[] = "'utc' can't be null";
        }
        if ($this->container['isoLocal'] === null) {
            $invalidProperties[] = "'isoLocal' can't be null";
        }
        if ($this->container['rfc2822'] === null) {
            $invalidProperties[] = "'rfc2822' can't be null";
        }
        if ($this->container['human'] === null) {
            $invalidProperties[] = "'human' can't be null";
        }
        if ($this->container['dayNumber'] === null) {
            $invalidProperties[] = "'dayNumber' can't be null";
        }
        if (($this->container['dayNumber'] > 7)) {
            $invalidProperties[] = "invalid value for 'dayNumber', must be smaller than or equal to 7.";
        }

        if (($this->container['dayNumber'] < 1)) {
            $invalidProperties[] = "invalid value for 'dayNumber', must be bigger than or equal to 1.";
        }

        if ($this->container['dayShort'] === null) {
            $invalidProperties[] = "'dayShort' can't be null";
        }
        if ($this->container['dayFull'] === null) {
            $invalidProperties[] = "'dayFull' can't be null";
        }
        if ($this->container['timezone'] === null) {
            $invalidProperties[] = "'timezone' can't be null";
        }
        if ($this->container['offset'] === null) {
            $invalidProperties[] = "'offset' can't be null";
        }
        if ($this->container['dst'] === null) {
            $invalidProperties[] = "'dst' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets unix
     *
     * @return int
     */
    public function getUnix()
    {
        return $this->container['unix'];
    }

    /**
     * Sets unix
     *
     * @param int $unix unix
     *
     * @return self
     */
    public function setUnix($unix)
    {
        if (is_null($unix)) {
            throw new \InvalidArgumentException('non-nullable unix cannot be null');
        }
        $this->container['unix'] = $unix;

        return $this;
    }

    /**
     * Gets unixMs
     *
     * @return int
     */
    public function getUnixMs()
    {
        return $this->container['unixMs'];
    }

    /**
     * Sets unixMs
     *
     * @param int $unixMs unixMs
     *
     * @return self
     */
    public function setUnixMs($unixMs)
    {
        if (is_null($unixMs)) {
            throw new \InvalidArgumentException('non-nullable unixMs cannot be null');
        }
        $this->container['unixMs'] = $unixMs;

        return $this;
    }

    /**
     * Gets utc
     *
     * @return \DateTime
     */
    public function getUtc()
    {
        return $this->container['utc'];
    }

    /**
     * Sets utc
     *
     * @param \DateTime $utc utc
     *
     * @return self
     */
    public function setUtc($utc)
    {
        if (is_null($utc)) {
            throw new \InvalidArgumentException('non-nullable utc cannot be null');
        }
        $this->container['utc'] = $utc;

        return $this;
    }

    /**
     * Gets isoLocal
     *
     * @return string
     */
    public function getIsoLocal()
    {
        return $this->container['isoLocal'];
    }

    /**
     * Sets isoLocal
     *
     * @param string $isoLocal isoLocal
     *
     * @return self
     */
    public function setIsoLocal($isoLocal)
    {
        if (is_null($isoLocal)) {
            array_push($this->openAPINullablesSetToNull, 'isoLocal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('isoLocal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['isoLocal'] = $isoLocal;

        return $this;
    }

    /**
     * Gets rfc2822
     *
     * @return string
     */
    public function getRfc2822()
    {
        return $this->container['rfc2822'];
    }

    /**
     * Sets rfc2822
     *
     * @param string $rfc2822 rfc2822
     *
     * @return self
     */
    public function setRfc2822($rfc2822)
    {
        if (is_null($rfc2822)) {
            throw new \InvalidArgumentException('non-nullable rfc2822 cannot be null');
        }
        $this->container['rfc2822'] = $rfc2822;

        return $this;
    }

    /**
     * Gets human
     *
     * @return string
     */
    public function getHuman()
    {
        return $this->container['human'];
    }

    /**
     * Sets human
     *
     * @param string $human human
     *
     * @return self
     */
    public function setHuman($human)
    {
        if (is_null($human)) {
            throw new \InvalidArgumentException('non-nullable human cannot be null');
        }
        $this->container['human'] = $human;

        return $this;
    }

    /**
     * Gets dayNumber
     *
     * @return int
     */
    public function getDayNumber()
    {
        return $this->container['dayNumber'];
    }

    /**
     * Sets dayNumber
     *
     * @param int $dayNumber dayNumber
     *
     * @return self
     */
    public function setDayNumber($dayNumber)
    {
        if (is_null($dayNumber)) {
            throw new \InvalidArgumentException('non-nullable dayNumber cannot be null');
        }

        if (($dayNumber > 7)) {
            throw new \InvalidArgumentException('invalid value for $dayNumber when calling TimezoneMatch., must be smaller than or equal to 7.');
        }
        if (($dayNumber < 1)) {
            throw new \InvalidArgumentException('invalid value for $dayNumber when calling TimezoneMatch., must be bigger than or equal to 1.');
        }

        $this->container['dayNumber'] = $dayNumber;

        return $this;
    }

    /**
     * Gets dayShort
     *
     * @return string
     */
    public function getDayShort()
    {
        return $this->container['dayShort'];
    }

    /**
     * Sets dayShort
     *
     * @param string $dayShort dayShort
     *
     * @return self
     */
    public function setDayShort($dayShort)
    {
        if (is_null($dayShort)) {
            throw new \InvalidArgumentException('non-nullable dayShort cannot be null');
        }
        $this->container['dayShort'] = $dayShort;

        return $this;
    }

    /**
     * Gets dayFull
     *
     * @return string
     */
    public function getDayFull()
    {
        return $this->container['dayFull'];
    }

    /**
     * Sets dayFull
     *
     * @param string $dayFull dayFull
     *
     * @return self
     */
    public function setDayFull($dayFull)
    {
        if (is_null($dayFull)) {
            throw new \InvalidArgumentException('non-nullable dayFull cannot be null');
        }
        $this->container['dayFull'] = $dayFull;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone timezone
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets formatted
     *
     * @return string|null
     */
    public function getFormatted()
    {
        return $this->container['formatted'];
    }

    /**
     * Sets formatted
     *
     * @param string|null $formatted formatted
     *
     * @return self
     */
    public function setFormatted($formatted)
    {
        if (is_null($formatted)) {
            throw new \InvalidArgumentException('non-nullable formatted cannot be null');
        }
        $this->container['formatted'] = $formatted;

        return $this;
    }

    /**
     * Gets offset
     *
     * @return int
     */
    public function getOffset()
    {
        return $this->container['offset'];
    }

    /**
     * Sets offset
     *
     * @param int $offset offset
     *
     * @return self
     */
    public function setOffset($offset)
    {
        if (is_null($offset)) {
            throw new \InvalidArgumentException('non-nullable offset cannot be null');
        }
        $this->container['offset'] = $offset;

        return $this;
    }

    /**
     * Gets dst
     *
     * @return bool
     */
    public function getDst()
    {
        return $this->container['dst'];
    }

    /**
     * Sets dst
     *
     * @param bool $dst dst
     *
     * @return self
     */
    public function setDst($dst)
    {
        if (is_null($dst)) {
            throw new \InvalidArgumentException('non-nullable dst cannot be null');
        }
        $this->container['dst'] = $dst;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


