# coding: utf-8

"""
    TimeLogic API — Direct Customer Access

    Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class JwkKey(BaseModel):
    """
    JwkKey
    """ # noqa: E501
    kty: StrictStr
    crv: StrictStr
    alg: StrictStr
    use: StrictStr
    kid: StrictStr
    x: StrictStr
    __properties: ClassVar[List[str]] = ["kty", "crv", "alg", "use", "kid", "x"]

    @field_validator('kty')
    def kty_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['OKP']):
            raise ValueError("must be one of enum values ('OKP')")
        return value

    @field_validator('crv')
    def crv_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Ed25519']):
            raise ValueError("must be one of enum values ('Ed25519')")
        return value

    @field_validator('alg')
    def alg_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['EdDSA']):
            raise ValueError("must be one of enum values ('EdDSA')")
        return value

    @field_validator('use')
    def use_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['sig']):
            raise ValueError("must be one of enum values ('sig')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JwkKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JwkKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kty": obj.get("kty"),
            "crv": obj.get("crv"),
            "alg": obj.get("alg"),
            "use": obj.get("use"),
            "kid": obj.get("kid"),
            "x": obj.get("x")
        })
        return _obj


