# coding: utf-8

"""
    TimeLogic API | A World Time API

    Official public API contract for TimeLogic API.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - the API supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`

    The version of the OpenAPI document: 1.0.0
    Generated by TimeLogic API SDK generator (https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from timelogic_direct_api.models.timezone_match import TimezoneMatch
from typing import Optional, Set
from typing_extensions import Self

class TimezoneOffsetResponse(BaseModel):
    """
    Offset-based timezone lookup result with `matching_zones` for the current request-time offset match.
    """ # noqa: E501
    unix: StrictInt
    unix_ms: StrictInt
    utc: datetime
    iso_local: Optional[StrictStr]
    rfc2822: StrictStr
    human: StrictStr
    day_number: Annotated[int, Field(le=7, strict=True, ge=1)]
    day_short: StrictStr
    day_full: StrictStr
    timezone: Optional[StrictStr]
    formatted: Optional[StrictStr] = None
    offset: StrictInt
    dst: StrictBool
    matching_zones: List[TimezoneMatch]
    __properties: ClassVar[List[str]] = ["unix", "unix_ms", "utc", "iso_local", "rfc2822", "human", "day_number", "day_short", "day_full", "timezone", "formatted", "offset", "dst", "matching_zones"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TimezoneOffsetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in matching_zones (list)
        _items = []
        if self.matching_zones:
            for _item_matching_zones in self.matching_zones:
                if _item_matching_zones:
                    _items.append(_item_matching_zones.to_dict())
            _dict['matching_zones'] = _items
        # set to None if iso_local (nullable) is None
        # and model_fields_set contains the field
        if self.iso_local is None and "iso_local" in self.model_fields_set:
            _dict['iso_local'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TimezoneOffsetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unix": obj.get("unix"),
            "unix_ms": obj.get("unix_ms"),
            "utc": obj.get("utc"),
            "iso_local": obj.get("iso_local"),
            "rfc2822": obj.get("rfc2822"),
            "human": obj.get("human"),
            "day_number": obj.get("day_number"),
            "day_short": obj.get("day_short"),
            "day_full": obj.get("day_full"),
            "timezone": obj.get("timezone"),
            "formatted": obj.get("formatted"),
            "offset": obj.get("offset"),
            "dst": obj.get("dst"),
            "matching_zones": [TimezoneMatch.from_dict(_item) for _item in obj["matching_zones"]] if obj.get("matching_zones") is not None else None
        })
        return _obj


