/*
 * TimeLogic API | A World Time API
 *
 * Official public API contract for TimeLogic API.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - the API supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://github.com/TimeLogic-API-LLC/timelogic-api-sdks.git
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarResponse {
    #[serde(rename = "unix")]
    pub unix: i64,
    #[serde(rename = "unix_ms")]
    pub unix_ms: i64,
    #[serde(rename = "utc")]
    pub utc: String,
    #[serde(rename = "iso_local", deserialize_with = "Option::deserialize")]
    pub iso_local: Option<String>,
    #[serde(rename = "rfc2822")]
    pub rfc2822: String,
    #[serde(rename = "human")]
    pub human: String,
    #[serde(rename = "day_number")]
    pub day_number: i32,
    #[serde(rename = "day_short")]
    pub day_short: String,
    #[serde(rename = "day_full")]
    pub day_full: String,
    #[serde(rename = "timezone", deserialize_with = "Option::deserialize")]
    pub timezone: Option<String>,
    #[serde(rename = "formatted", skip_serializing_if = "Option::is_none")]
    pub formatted: Option<String>,
    #[serde(rename = "year")]
    pub year: i32,
    #[serde(rename = "month")]
    pub month: i32,
    #[serde(rename = "month_name")]
    pub month_name: String,
    #[serde(rename = "day")]
    pub day: i32,
    #[serde(rename = "week_number", skip_serializing_if = "Option::is_none")]
    pub week_number: Option<i32>,
}

impl CalendarResponse {
    pub fn new(unix: i64, unix_ms: i64, utc: String, iso_local: Option<String>, rfc2822: String, human: String, day_number: i32, day_short: String, day_full: String, timezone: Option<String>, year: i32, month: i32, month_name: String, day: i32) -> CalendarResponse {
        CalendarResponse {
            unix,
            unix_ms,
            utc,
            iso_local,
            rfc2822,
            human,
            day_number,
            day_short,
            day_full,
            timezone,
            formatted: None,
            year,
            month,
            month_name,
            day,
            week_number: None,
        }
    }
}

