/*
 * TimeLogic API — Direct Customer Access
 *
 * Public direct-access contract for the TimeLogic gateway.  This public spec excludes `/healthz` and the shared clock asset routes. It keeps `/.well-known/time-api-public-key`, `/v1/time/clock`, and signed JSON response controls because public consumers may need them.  Authentication: - direct access supports `Authorization: Bearer <token>`, `X-API-Key`, and `api_key` query credentials - RapidAPI access uses `X-RapidAPI-Key` and `X-RapidAPI-Host`; the SDKs expose this as a `rapidApi` transport option that accepts only the RapidAPI key  Behavioral notes: - all documented operations are `GET` - only one selector family may be used at a time - current and convert support bulk only through one comma-separated `tz`, `ip`, or `offset` selector - add, diff, calendar, dst, elapsed, timezone, and clock are single-target routes - credentials are extracted in Authorization, X-API-Key, then api_key query order; conflicting values are rejected - the first server is the default direct API host. The second server is the RapidAPI gateway and can be selected or overridden by SDK configuration - `sign` is available on supported JSON routes and is not supported on `/v1/time/clock`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwkKey {
    #[serde(rename = "kty")]
    pub kty: Kty,
    #[serde(rename = "crv")]
    pub crv: Crv,
    #[serde(rename = "alg")]
    pub alg: Alg,
    #[serde(rename = "use")]
    pub r#use: Use,
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "x")]
    pub x: String,
}

impl JwkKey {
    pub fn new(kty: Kty, crv: Crv, alg: Alg, r#use: Use, kid: String, x: String) -> JwkKey {
        JwkKey {
            kty,
            crv,
            alg,
            r#use,
            kid,
            x,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kty {
    #[serde(rename = "OKP")]
    Okp,
}

impl Default for Kty {
    fn default() -> Kty {
        Self::Okp
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Crv {
    #[serde(rename = "Ed25519")]
    Ed25519,
}

impl Default for Crv {
    fn default() -> Crv {
        Self::Ed25519
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Alg {
    #[serde(rename = "EdDSA")]
    EdDsa,
}

impl Default for Alg {
    fn default() -> Alg {
        Self::EdDsa
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Use {
    #[serde(rename = "sig")]
    Sig,
}

impl Default for Use {
    fn default() -> Use {
        Self::Sig
    }
}

